### ISSUE TITLE
指令精调报错

### ISSUE THREAD

**Issue by cccgw** [ymcui/Chinese-LLaMA-Alpaca-2#107]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

基于alpaca精调合并后的chinese-alpaca-2-7b-hf，进行自己领域的指令精调， 出现以下报错：
```
/root/miniconda3/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
.....
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
  0%|          | 0/36712 [00:02<?, ?it/s]
```
run_sft.sh内容如下：
```
lr=1e-4
lora_rank=64
lora_alpha=128
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/root/autodl-tmp/data/chinese-alpaca-2-7b-hf
chinese_tokenizer_path=/root/autodl-tmp/data/chinese-alpaca-2-7b-hf
dataset_dir=/root/autodl-tmp/data/datasets/instruct-data
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=8
output_dir=/root/autodl-tmp/data/alpaca-2-7b
validation_file=/root/autodl-tmp/data/datasets/eval-data/eval_alpaca_51k.json

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed 654 \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 100 \
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False
```

### 依赖情况（代码类问题务必提供）

```
peft                           0.3.0.dev0
sentence-transformers          2.2.2
torch                          2.0.0+cu118
torchvision                    0.15.1+cu118
transformers                   4.30.2
```

### 运行日志或截图

```
[INFO|trainer.py:1786] 2023-08-09 15:33:38,185 >> ***** Running training *****
[INFO|trainer.py:1787] 2023-08-09 15:33:38,185 >>   Num examples = 293,703
[INFO|trainer.py:1788] 2023-08-09 15:33:38,185 >>   Num Epochs = 1
[INFO|trainer.py:1789] 2023-08-09 15:33:38,185 >>   Instantaneous batch size per device = 1
[INFO|trainer.py:1790] 2023-08-09 15:33:38,185 >>   Total train batch size (w. parallel, distributed & accumulation) = 8
[INFO|trainer.py:1791] 2023-08-09 15:33:38,185 >>   Gradient Accumulation steps = 8
[INFO|trainer.py:1792] 2023-08-09 15:33:38,185 >>   Total optimization steps = 36,712
[INFO|trainer.py:1793] 2023-08-09 15:33:38,189 >>   Number of trainable parameters = 159,907,840
  0%|          | 0/36712 [00:00<?, ?it/s][WARNING|logging.py:295] 2023-08-09 15:33:38,226 >> `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
/root/miniconda3/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/autodl-tmp/data/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_sft_with_peft.py:438 in    │
│ <module>                                                                                         │
│                                                                                                  │
│   435                                                                                            │
│   436                                                                                            │
│   437 if __name__ == "__main__":                                                                 │
│ ❱ 438 │   main()                                                                                 │
│   439                                                                                            │
│                                                                                                  │
│ /root/autodl-tmp/data/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_sft_with_peft.py:411 in    │
│ main                                                                                             │
│                                                                                                  │
│   408 │   │   │   checkpoint = training_args.resume_from_checkpoint                              │
│   409 │   │   elif last_checkpoint is not None:                                                  │
│   410 │   │   │   checkpoint = last_checkpoint                                                   │
│ ❱ 411 │   │   train_result = trainer.train(resume_from_checkpoint=checkpoint)                    │
│   412 │   │                                                                                      │
│   413 │   │   metrics = train_result.metrics                                                     │
│   414                                                                                            │
│                                                                                                  │
│ /root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py:1645 in train               │
│                                                                                                  │
│   1642 │   │   inner_training_loop = find_executable_batch_size(                                 │
│   1643 │   │   │   self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size  │
│   1644 │   │   )                                                                                 │
│ ❱ 1645 │   │   return inner_training_loop(                                                       │
│   1646 │   │   │   args=args,                                                                    │
│   1647 │   │   │   resume_from_checkpoint=resume_from_checkpoint,                                │
│   1648 │   │   │   trial=trial,                                                                  │
│                                                                                                  │
│ /root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py:1938 in                     │
│ _inner_training_loop                                                                             │
│                                                                                                  │
│   1935 │   │   │   │   │   self.control = self.callback_handler.on_step_begin(args, self.state,  │
│   1936 │   │   │   │                                                                             │
│   1937 │   │   │   │   with self.accelerator.accumulate(model):                                  │
│ ❱ 1938 │   │   │   │   │   tr_loss_step = self.training_step(model, inputs)                      │
│   1939 │   │   │   │                                                                             │
│   1940 │   │   │   │   if (                                                                      │
│   1941 │   │   │   │   │   args.logging_nan_inf_filter                                           │
│                                                                                                  │
│ /root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py:2770 in training_step       │
│                                                                                                  │
│   2767 │   │   │   with amp.scale_loss(loss, self.optimizer) as scaled_loss:                     │
│   2768 │   │   │   │   scaled_loss.backward()                                                    │
│   2769 │   │   else:                                                                             │
│ ❱ 2770 │   │   │   self.accelerator.backward(loss)                                               │
│   2771 │   │                                                                                     │
│   2772 │   │   return loss.detach() / self.args.gradient_accumulation_steps                      │
│   2773                                                                                           │
│                                                                                                  │
│ /root/miniconda3/lib/python3.8/site-packages/accelerate/accelerator.py:1815 in backward          │
│                                                                                                  │
│   1812 │   │   │   # deepspeed handles loss scaling by gradient_accumulation_steps in its `back  │
│   1813 │   │   │   loss = loss / self.gradient_accumulation_steps                                │
│   1814 │   │   if self.distributed_type == DistributedType.DEEPSPEED:                            │
│ ❱ 1815 │   │   │   self.deepspeed_engine_wrapped.backward(loss, **kwargs)                        │
│   1816 │   │   elif self.distributed_type == DistributedType.MEGATRON_LM:                        │
│   1817 │   │   │   return                                                                        │
│   1818 │   │   elif self.scaler is not None:                                                     │
│                                                                                                  │
│ /root/miniconda3/lib/python3.8/site-packages/accelerate/utils/deepspeed.py:167 in backward       │
│                                                                                                  │
│   164 │                                                                                          │
│   165 │   def backward(self, loss, **kwargs):                                                    │
│   166 │   │   # runs backpropagation and handles mixed precision                                 │
│ ❱ 167 │   │   self.engine.backward(loss, **kwargs)                                               │
│   168 │   │                                                                                      │
│   169 │   │   # Deepspeed's `engine.step` performs the following operations:                     │
│   170 │   │   # - gradient accumulation check                                                    │
│                                                                                                  │
│ /root/miniconda3/lib/python3.8/site-packages/deepspeed/utils/nvtx.py:15 in wrapped_fn            │
│                                                                                                  │
│   12 │                                                                                           │
│   13 │   def wrapped_fn(*args, **kwargs):                                                        │
│   14 │   │   get_accelerator().range_push(func.__qualname__)                                     │
│ ❱ 15 │   │   ret_val = func(*args, **kwargs)                                                     │
│   16 │   │   get_accelerator().range_pop()                                                       │
│   17 │   │   return ret_val                                                                      │
│   18                                                                                             │
│                                                                                                  │
│ /root/miniconda3/lib/python3.8/site-packages/deepspeed/runtime/engine.py:1862 in backward        │
│                                                                                                  │
│   1859 │   │                                                                                     │
│   1860 │   │   if self.zero_optimization():                                                      │
│   1861 │   │   │   self.optimizer.is_gradient_accumulation_boundary = self.is_gradient_accumula  │
│ ❱ 1862 │   │   │   self.optimizer.backward(loss, retain_graph=retain_graph)                      │
│   1863 │   │   elif self.amp_enabled():                                                          │
│   1864 │   │   │   # AMP requires delaying unscale when inside gradient accumulation boundaries  │
│   1865 │   │   │   # https://nvidia.github.io/apex/advanced.html#gradient-accumulation-across-i  │
│                                                                                                  │
│ /root/miniconda3/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py:1901 in     │
│ backward                                                                                         │
│                                                                                                  │
│   1898 │   │   │   scaled_loss = self.external_loss_scale * loss                                 │
│   1899 │   │   │   scaled_loss.backward()                                                        │
│   1900 │   │   else:                                                                             │
│ ❱ 1901 │   │   │   self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)            │
│   1902 │                                                                                         │
│   1903 │   def check_overflow(self, partition_gradients=True):                                   │
│   1904 │   │   self._check_overflow(partition_gradients)                                         │
│                                                                                                  │
│ /root/miniconda3/lib/python3.8/site-packages/deepspeed/runtime/fp16/loss_scaler.py:63 in         │
│ backward                                                                                         │
│                                                                                                  │
│    60 │                                                                                          │
│    61 │   def backward(self, loss, retain_graph=False):                                          │
│    62 │   │   scaled_loss = loss * self.loss_scale                                               │
│ ❱  63 │   │   scaled_loss.backward(retain_graph=retain_graph)                                    │
│    64 │   │   # print(f'LossScalerBackward: {scaled_loss=}')                                     │
│    65                                                                                            │
│    66                                                                                            │
│                                                                                                  │
│ /root/miniconda3/lib/python3.8/site-packages/torch/_tensor.py:487 in backward                    │
│                                                                                                  │
│    484 │   │   │   │   create_graph=create_graph,                                                │
│    485 │   │   │   │   inputs=inputs,                                                            │
│    486 │   │   │   )                                                                             │
│ ❱  487 │   │   torch.autograd.backward(                                                          │
│    488 │   │   │   self, gradient, retain_graph, create_graph, inputs=inputs                     │
│    489 │   │   )                                                                                 │
│    490                                                                                           │
│                                                                                                  │
│ /root/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py:200 in backward          │
│                                                                                                  │
│   197 │   # The reason we repeat same the comment below is that                                  │
│   198 │   # some Python versions print out the first line of a multi-line function               │
│   199 │   # calls in the traceback and some print out the last line                              │
│ ❱ 200 │   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the bac   │
│   201 │   │   tensors, grad_tensors_, retain_graph, create_graph, inputs,                        │
│   202 │   │   allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to ru   │
│   203                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
  0%|          | 0/36712 [00:02<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3763) of binary: /root/miniconda3/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm_sft_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-09_15:33:45
  host      : autodl-container-84b1118916-c3a066dc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3763)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

```

**Comment by cccgw** [comment]
换了台机器，有相同的问题，可能是配置原因吗？

**Comment by airaria** [comment]
没遇到过这种情况。建议按[requirements.txt](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/requirements.txt)的要求配置环境，同时把accelerate、deepspeed等库更新到最新版本

**Comment by wangzhonghai** [comment]
代码里只能lora训练，我想全微调，然后就把lora给删除了，没删干净，和你一样的错，估计是你的参数都固定了，没有可微调的参数，就会报这个错，你固定模型全部参数，纯用lora也不行，好像要加peft的一个模块，或者你lora微调的时候放开embedding层

**Comment by wangzhonghai** [comment]
还有这个程序训练的很慢啊，我用stage3，30w的数据，batch设置为8，8卡，训练98个小时一个epoch，人麻了，我用stage3，9个小时一个epoch，但是一用到llama2损失就NaN

**Comment by wangzhonghai** [comment]
不知道是不是梯度太大，还是精度太高，或者溢出了。

**Comment by better629** [comment]
I have tried remove `--gradient_checkpointing` and `--modules_to_save ${modules_to_save}` which would solve `xxx require grad and does not have a grad_fn` problem.

**Comment by cccgw** [comment]
我也是删掉了--gradient_checkpointing 后可以正常跑，谢谢。
