### ISSUE TITLE
提示张量梯度索引缺失

### ISSUE THREAD

**Issue by wangzhonghai** [ymcui/Chinese-LLaMA-Alpaca-2#121]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
没有使用lora微调

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```torchrun --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed $RANDOM \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 100 \
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 1024 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --torch_dtype float16 \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False


### 运行日志或截图

```
# 请在此处粘贴运行日志
```[WARNING|logging.py:295] 2023-08-11 15:00:08,865 >> `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
/home/fist/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Traceback (most recent call last):
  File "/home/fist/Belle/Chinese-LLaMA-Alpaca-2-main/scripts/training/run_clm_sft_with_peft.py", line 438, in <module>
    main()
  File "/home/fist/Belle/Chinese-LLaMA-Alpaca-2-main/scripts/training/run_clm_sft_with_peft.py", line 411, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/fist/miniconda3/envs/llama2/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/fist/miniconda3/envs/llama2/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/fist/miniconda3/envs/llama2/lib/python3.10/site-packages/transformers/trainer.py", line 2665, in training_step
    self.accelerator.backward(loss)
  File "/home/fist/miniconda3/envs/llama2/lib/python3.10/site-packages/accelerate/accelerator.py", line 1847, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/home/fist/miniconda3/envs/llama2/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/home/fist/miniconda3/envs/llama2/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/fist/miniconda3/envs/llama2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1895, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/home/fist/miniconda3/envs/llama2/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1902, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/home/fist/miniconda3/envs/llama2/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/home/fist/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/fist/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by wangzhonghai** [comment]
有办法设置offload，使用stage3吗，我在使用stage3的时候，训练的损失总是出现NaN，是必须使用fp32训练吗
