### ISSUE TITLE
推理SFT模型报错

### ISSUE THREAD

**Issue by longkeyy** [ymcui/Chinese-LLaMA-Alpaca-2#157]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型推理

### 基础模型

Alpaca-2-7B

### 操作系统

macOS

### 详细描述问题

```
python openai_api_server.py --base_model ./base_model/chinese-alpaca-2-7b-hf \
 --lora_model ./sft/sft_lora_model \
 --only_cpu
```

### 依赖情况（代码类问题务必提供）

```
accelerate==0.21.0
annotated-types==0.5.0
anyio==3.7.1
bitsandbytes==0.41.0
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.6
exceptiongroup==1.1.3
fastapi==0.101.1
filelock==3.12.2
fsspec==2023.6.0
h11==0.14.0
huggingface-hub==0.16.4
idna==3.4
Jinja2==3.1.2
MarkupSafe==2.1.3
mpmath==1.3.0
networkx==3.1
numpy==1.25.2
packaging==23.1
peft @ git+https://github.com/huggingface/peft.git@13e53fc7ee5d89d59b16523051006dddf0fb7a49
psutil==5.9.5
pydantic==2.1.1
pydantic_core==2.4.0
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
safetensors==0.3.2
scipy==1.11.1
sentencepiece==0.1.97
shortuuid==1.0.11
sniffio==1.3.0
sse-starlette==1.6.5
starlette==0.27.0
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
tqdm==4.66.1
transformers==4.31.0
typing_extensions==4.7.1
urllib3==2.0.4
uvicorn==0.23.2

```

### 运行日志或截图

```
2023-08-19 00:59:20,503 - INFO - Started server process [40831]
2023-08-19 00:59:20,503 - INFO - Waiting for application startup.
2023-08-19 00:59:20,503 - INFO - Application startup complete.
2023-08-19 00:59:20,504 - INFO - Uvicorn running on http://0.0.0.0:19327 (Press CTRL+C to quit)
/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/transformers/generation/utils.py:1468: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on mps. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('mps') before running `.generate()`.
  warnings.warn(
2023-08-19 00:59:33,738 - INFO - 127.0.0.1:49160 - "POST /v1/chat/completions HTTP/1.1" 500
2023-08-19 00:59:33,738 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/longkeyy/PycharmProjects/local_openai/openai_api_server.py", line 322, in create_chat_completion
    output = predict(
  File "/Users/longkeyy/PycharmProjects/local_openai/openai_api_server.py", line 197, in predict
    generation_output = model.generate(
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/peft/peft_model.py", line 581, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 646, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Placeholder storage has not been allocated on MPS device!
^C2023-08-19 00:59:44,953 - INFO - Shutting down
2023-08-19 00:59:45,054 - INFO - Waiting for application shutdown.
2023-08-19 00:59:45,054 - INFO - Application shutdown complete.
2023-08-19 00:59:45,054 - INFO - Finished server process [40831]

      ~/PycharmProjects/local_openai ▓▒░ ./run_openai.sh                                                                                                           ░▒▓ ✔  took 1m 31s    local_openai 🐍 
usage: openai_api_server.py [-h] --base_model BASE_MODEL [--lora_model LORA_MODEL] [--tokenizer_path TOKENIZER_PATH] [--gpus GPUS] [--load_in_8bit] [--load_in_4bit] [--only_cpu] [--alpha ALPHA]
openai_api_server.py: error: unrecognized arguments: --cpu_only

      ~/PycharmProjects/local_openai ▓▒░ ./run_openai.sh -h                                                                                                                      ░▒▓ 2 ✘  local_openai 🐍 
usage: openai_api_server.py [-h] --base_model BASE_MODEL [--lora_model LORA_MODEL] [--tokenizer_path TOKENIZER_PATH] [--gpus GPUS] [--load_in_8bit] [--load_in_4bit] [--only_cpu] [--alpha ALPHA]

options:
  -h, --help            show this help message and exit
  --base_model BASE_MODEL
  --lora_model LORA_MODEL
                        If None, perform inference on the base model
  --tokenizer_path TOKENIZER_PATH
  --gpus GPUS
  --load_in_8bit        Load the model in 8bit mode
  --load_in_4bit        Load the model in 4bit mode
  --only_cpu            Only use CPU for inference
  --alpha ALPHA         The scaling factor of NTK method, can be a float or 'auto'.

      ~/PycharmProjects/local_openai ▓▒░ ./run_openai.sh                                                                                                                           ░▒▓ ✔  local_openai 🐍 
usage: openai_api_server.py [-h] --base_model BASE_MODEL [--lora_model LORA_MODEL] [--tokenizer_path TOKENIZER_PATH] [--gpus GPUS] [--load_in_8bit] [--load_in_4bit] [--only_cpu] [--alpha ALPHA]
openai_api_server.py: error: unrecognized arguments: True

      ~/PycharmProjects/local_openai ▓▒░ ./run_openai.sh                                                                                                                         ░▒▓ 2 ✘  local_openai 🐍 
/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Xformers is not installed correctly. If you want to use memory_efficient_attention use the following command to install Xformers
pip install xformers.
USE_MEM_EFF_ATTENTION:  False
STORE_KV_BEFORE_ROPE: False
Apply NTK scaling with ALPHA=1.0
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.19s/it]
Vocab of the base model: 55296
Vocab of the tokenizer: 55296
loading peft model
2023-08-19 01:01:57,472 - INFO - Started server process [41167]
2023-08-19 01:01:57,472 - INFO - Waiting for application startup.
2023-08-19 01:01:57,473 - INFO - Application startup complete.
2023-08-19 01:01:57,473 - INFO - Uvicorn running on http://0.0.0.0:19327 (Press CTRL+C to quit)
2023-08-19 01:02:03,708 - INFO - 127.0.0.1:52050 - "POST /v1/chat/completions HTTP/1.1" 500
2023-08-19 01:02:03,708 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/longkeyy/PycharmProjects/local_openai/openai_api_server.py", line 322, in create_chat_completion
    output = predict(
  File "/Users/longkeyy/PycharmProjects/local_openai/openai_api_server.py", line 197, in predict
    generation_output = model.generate(
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/peft/peft_model.py", line 581, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/Users/longkeyy/miniconda3/envs/local_openai/lib/python3.10/site-packages/transformers/generation/utils.py", line 2678, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by ymcui** [comment]
`--base_model`指定的`./base_model/chinese-alpaca-2-7b-hf`已经是完整模型了，不要再指定`lora_model`了。
