### ISSUE TITLE
peft版本导致的FP16

### ISSUE THREAD

**Issue by xxw1995** [ymcui/Chinese-LLaMA-Alpaca-2#164]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

None

### 操作系统

Linux

### 详细描述问题

```
使用0.3.0.dev0版本peft报fp16的错误，查到资料显示升级至最新版本的peft才能解决问题，但是最新版本的peft和项目要求冲突，请问这个在不升级peft的情况下，怎么解决？硬件为单卡v100

执行脚本
python3 run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed 32 \
    --fp16 \
    --num_train_epochs 1 \ 
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \ 
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \ 
    --block_size 1024 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --gradient_checkpointing \
```

### 依赖情况（代码类问题务必提供）

```
peft                     0.3.0.dev0
torch                    2.0.1
transformers             4.31.0
```

### 运行日志或截图

```
  warnings.warn(
[INFO|trainer.py:1686] 2023-08-22 09:47:58,508 >> ***** Running training *****
[INFO|trainer.py:1687] 2023-08-22 09:47:58,509 >>   Num examples = 3,596
[INFO|trainer.py:1688] 2023-08-22 09:47:58,509 >>   Num Epochs = 1 
[INFO|trainer.py:1689] 2023-08-22 09:47:58,509 >>   Instantaneous batch size per device = 1 
[INFO|trainer.py:1692] 2023-08-22 09:47:58,509 >>   Total train batch size (w. parallel, distributed & accumulation) = 8 
[INFO|trainer.py:1693] 2023-08-22 09:47:58,509 >>   Gradient Accumulation steps = 8 
[INFO|trainer.py:1694] 2023-08-22 09:47:58,509 >>   Total optimization steps = 449 
[INFO|trainer.py:1695] 2023-08-22 09:47:58,514 >>   Number of trainable parameters = 597,524,480
trainable params: 597524480 || all params: 13285708800 || trainable%: 4.497497943052914
^M  0%|          | 0/449 [00:00<?, ?it/s][WARNING|logging.py:295] 2023-08-22 09:47:58,540 >> `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
Traceback (most recent call last):
  File "/opt/tiger/xuxuanwen/personal/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_pt_with_peft.py", line 637, in <module>
    main()
  File "/opt/tiger/xuxuanwen/personal/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_pt_with_peft.py", line 605, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.9/site-packages/transformers/trainer.py", line 1867, in _inner_training_loop
    self.accelerator.clip_grad_norm_(
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.9/site-packages/accelerate/accelerator.py", line 1925, in clip_grad_norm_
    self.unscale_gradients()
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.9/site-packages/accelerate/accelerator.py", line 1888, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
^M  0%|          | 0/449 [00:06<?, ?it/s]
```

**Comment by xxw1995** [comment]
补充一下 加载的模型是chinese-llama-2-13b-hf

**Comment by xxw1995** [comment]
详细描述问题中硬件描述有误 硬件为单卡A100

**Comment by luhairong11** [comment]
我把输入参数 --torch_dtype float16 改成了float32可以运行

**Comment by xxw1995** [comment]
> 我把输入参数 --torch_dtype float16 改成了float32可以运行

请问你是哪个版本的transformer?

**Comment by luhairong11** [comment]
> > 我把输入参数 --torch_dtype float16 改成了float32可以运行
> 
> 请问你是哪个版本的transformer?
我的transformers [4.31.0，但是我也没跑起来，有其他问题](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/issues/166)

**Comment by xxw1995** [comment]
> > > 我把输入参数 --torch_dtype float16 改成了float32可以运行
> > 
> > 
> > 请问你是哪个版本的transformer?
> > 我的transformers [4.31.0，但是我也没跑起来，有其他问题](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/issues/166)

一样 目前报错

**Comment by Qznan** [comment]
将`--torch_dtype`参数去掉或者设置为`--torch_dtype auto`就好了

**Comment by iMountTai** [comment]
为什么不用`torchrun`启动呢？[wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh)有明确的说明呀
