### ISSUE TITLE
关于langchain_qa.py中的device的设置问题？

### ISSUE THREAD

**Issue by Adonis2018** [ymcui/Chinese-LLaMA-Alpaca-2#180]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

## 运行
```
python  langchain_qa.py --file_path doc.txt --embedding_path /mnt/text2vec-large-chinese --model_path /mnt/chinese-alpaca-2-7b
```

## huggingface_pipeline.py中部分代码
`root/miniconda3/envs/myconda/lib/python3.9/site-packages/langchain/llms/huggingface_pipeline.py`
``` 
def from_model_id(
        cls,
        model_id: str,
        task: str,
        device: int = -1,  #这里device只能是int类型，加载模型时怎么使用两个GPU？
        model_kwargs: Optional[dict] = None,
        pipeline_kwargs: Optional[dict] = None,
        **kwargs: Any,
    ) -> LLM:
````

## langchain_qa.py中部分代码
```
from langchain import HuggingFacePipeline
……

  model = HuggingFacePipeline.from_model_id(model_id=model_path,
            task="text-generation",
            device=1,  #这里device只能是int类型，加载模型时怎么使用两个GPU？
            model_kwargs={
                          "torch_dtype" : load_type,
                          "low_cpu_mem_usage" : True,
                          "temperature": 0.2,
                          "max_length": 1000,
                          "repetition_penalty":1.1}
            )

```

### 运行日志或截图

```
(myconda) root@Zaox3g:/Chinese-LLaMA-Alpaca-2-main/scripts/langchain# python  langchain_qa.py --file_path doc.txt --embedding_path /mnt/text2vec-large-chinese --model_path /mnt/chinese-alpaca-2-7b
Loading the embedding model...
No sentence-transformers model found with name /mnt/text2vec-large-chinese. Creating a new one with MEAN pooling.
loading LLM...
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████| 2/2 [02:49<00:00, 84.80s/it]
Traceback (most recent call last):
  File "/Chinese-LLaMA-Alpaca-2-main/scripts/langchain/langchain_qa.py", line 73, in <module>
    model = HuggingFacePipeline.from_model_id(model_id=model_path,
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/langchain/llms/huggingface_pipeline.py", line 126, in from_model_id
    pipeline = hf_pipeline(
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/transformers/pipelines/__init__.py", line 988, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/transformers/pipelines/text_generation.py", line 63, in __init__
    super().__init__(*args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/transformers/pipelines/base.py", line 781, in __init__
    self.model.to(device)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1900, in to
    return super().to(*args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 1; 11.17 GiB total capacity; 10.86 GiB already allocated; 68.25 MiB free; 10.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by airaria** [comment]
如果langchain接口不支持直接使用多gpu，那需要修改langchain代码，比如：
```python
    @classmethod
    def from_model_id(
        cls,
        model_id: str,
        task: str,
        device: int = -1,
        model_kwargs: Optional[dict] = None,
        **kwargs: Any,
    ) -> LLM:
        """Construct the pipeline object from model_id and task."""
        try:
            from transformers import (
                AutoModelForCausalLM,
                AutoModelForSeq2SeqLM,
                AutoTokenizer,
            )
            from transformers import pipeline as hf_pipeline

        except ImportError:
            raise ValueError(
                "Could not import transformers python package. "
                "Please install it with `pip install transformers`."
            )

        _model_kwargs = model_kwargs or {}
        tokenizer = AutoTokenizer.from_pretrained(model_id, **_model_kwargs)

        try:
            if task == "text-generation":
                model = AutoModelForCausalLM.from_pretrained(model_id, **_model_kwargs) #在这里提供device_map
            elif task == "text2text-generation":
                model = AutoModelForSeq2SeqLM.from_pretrained(model_id, **_model_kwargs)
            else:
```

建议去langchain提问以获得更完善的解决方案。

**Comment by Adonis2018** [comment]
好的，谢谢回复，我以为是我的问题，现在明白了，原来langchain不支持双卡加载。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jediyoda36** [comment]
@Adonis2018 求问一下这个问题你后来解决了吗？我看langchain官方说可以用`device_map`替代`device`，但是我用`device_map`之后就只能用CPU来进行推理

**Comment by importTthis** [comment]
> @Adonis2018 求问一下这个问题你后来解决了吗？我看langchain官方说可以用`device_map`替代`device`，但是我用`device_map`之后就只能用CPU来进行推理

你有解决么，我今天也遇到了，指定device_map就只使用cpu了，怎么使用多gpu呀
