### ISSUE TITLE
bug: FileNotFoundError: Directory dataset_dir is neither a `Dataset` directory nor a `DatasetDict` directory.

### ISSUE THREAD

**Issue by XuJianzhi** [ymcui/Chinese-LLaMA-Alpaca-2#184]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-13B

### 操作系统

Linux

### 详细描述问题

我的运行程序：
```
########参数部分########
lr=1e-4
lora_rank=4
lora_alpha=16
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/data/model/ziqingyang__chinese-alpaca-2-13b/
dataset_dir=/data/code/Chinese-LLaMA-Alpaca-2-main/data
num_train_epochs=1
per_device_train_batch_size=2
per_device_eval_batch_size=2
gradient_accumulation_steps=8
output_dir=/data/model/output_save_13b
max_seq_length=1024

deepspeed_config_file=ds_zero2_no_offload.json

########启动命令########
torchrun --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${pretrained_model} \
    --dataset_dir ${dataset_dir} \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --num_train_epochs ${num_train_epochs} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 20 \
    --save_strategy steps \
    --save_total_limit 1 \
    --evaluation_strategy steps \
    --eval_steps 1000 \
    --save_steps 10000 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length ${max_seq_length} \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --validation_file ${dataset_dir}

```

为了确保数据无误，刻意将数据弄成仅有一条：
```
root@job-3833-1692798333-ldgck:/data/code/Chinese-LLaMA-Alpaca-2-main/data# cat aaa.json 
[
  {"instruction" : "你你你",
   "input" : "",
   "output" : "我我"
  }
 
]

```

### 依赖情况（代码类问题务必提供）

```
root@job-3833-1692798333-ldgck:/data/code/Chinese-LLaMA-Alpaca-2-main/data# pip list | grep -E 'transformers|peft|torch'
peft                    0.3.0.dev0
torch                   2.0.1
torchaudio              2.0.2
torchdata               0.6.1
torchelastic            0.2.2
torchtext               0.15.2
torchvision             0.15.2
transformers            4.31.0

```

### 运行日志或截图

```
Extracting data files: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 28339.89it/s]
Generating train split
08/24/2023 11:44:51 - INFO - datasets.builder - Generating train split
Generating train split: 0 examples [00:00, ? examples/s]
Traceback (most recent call last):
  File "/data/code/Chinese-LLaMA-Alpaca-2-main/scripts/training/build_dataset.py", line 68, in build_instruction_dataset
    processed_dataset = datasets.load_from_disk(cache_path)
  File "/opt/conda/lib/python3.10/site-packages/datasets/load.py", line 2235, in load_from_disk
    raise FileNotFoundError(
FileNotFoundError: Directory dataset_dir is neither a `Dataset` directory nor a `DatasetDict` directory.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/code/Chinese-LLaMA-Alpaca-2-main/scripts/training/run_clm_sft_with_peft.py", line 438, in <module>
    main()
  File "/data/code/Chinese-LLaMA-Alpaca-2-main/scripts/training/run_clm_sft_with_peft.py", line 324, in main
    eval_dataset = build_instruction_dataset(
  File "/data/code/Chinese-LLaMA-Alpaca-2-main/scripts/training/build_dataset.py", line 71, in build_instruction_dataset
    raw_dataset = load_dataset("json", data_files=file, cache_dir=cache_path)
  File "/opt/conda/lib/python3.10/site-packages/datasets/load.py", line 2136, in load_dataset
    builder_instance.download_and_prepare(
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 1813, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 1958, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4493) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm_sft_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-24_11:44:56
  host      : job-3833-1692798333-ldgck
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4493)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by airaria** [comment]
dataset_dir里的内容是什么？

**Comment by XuJianzhi** [comment]
> dataset_dir里的内容是什么？

root@job-3833-1692798333-ldgck:/data/code/Chinese-LLaMA-Alpaca-2-main/data# ls
aaa.json

**Comment by XuJianzhi** [comment]
> dataset_dir里的内容是什么？

刚发布的有问题，修改了，，，，就是用的这个文件夹内部唯一的aaa.json

**Comment by raultang** [comment]
@XuJianzhi 解决了么，我用7b遇到一样的问题，精调报这个错

**Comment by XuJianzhi** [comment]
> @XuJianzhi 解决了么，我用7b遇到一样的问题，精调报这个错

没，改用别的开源工程了

**Comment by yajingsunno** [comment]
> @XuJianzhi 解决了么，我用7b遇到一样的问题，精调报这个错

同样报了这个错误，有解决办法了吗？

**Comment by 96005900** [comment]
> 训练数据的格式应该是这样的： {"instruction":"问题一？","input":"","output":"答案一"} {"instruction":"问题二？","input":"","output":"答案二"} {"instruction":"问题三？","input":"","output":"答案三"}
> 
> 注意，头尾没有 [ 和 ] ， 行尾也没有英文逗号
> 
> 另外，在 .sh 的脚本中，validation_file 参数必须指定 validation file 的文件名，而不是目录。 如下： validation_file=/home/dataset/validation_data/validation.json

我就是这样设置的，还是报相同的错误

**Comment by 96005900** [comment]
这个错误根本无解，搜遍了issue也不知道问题在哪

**Comment by Kevinlinpr** [comment]
已解决，我同样遇到此问题，此问题的原因在于Datasets文件夹下的文件格式不对。

文件需要纯.txt文件

此问题可以关闭了

**Comment by Kevinlinpr** [comment]
https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/data/pt_sample_data.txt

请使用上述数据文件进行训练，一定要注意datasets文件夹下只能存在纯.txt文件
