### ISSUE TITLE
lora合并出现问题

### ISSUE THREAD

**Issue by Nasamars** [ymcui/Chinese-LLaMA-Alpaca-2#220]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
python Chinese-LLaMA-Alpaca-2-main/scripts/merge_llama2_with_chinese_lora_low_mem.py --base_model ../llama2/llama-2-7b-hf --lora_model ./chinese-alpaca-2-lora-7b

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

/opt/anaconda3/envs/HackUtil/lib/python3.9/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
================================================================================
Base model: ../llama2/llama-2-7b-hf
LoRA model: ./chinese-alpaca-2-lora-7b
Loading ./chinese-alpaca-2-lora-7b
Traceback (most recent call last):
  File "/Users/sylvain/AIGC/llama/alpaca2/Chinese-LLaMA-Alpaca-2-main/scripts/merge_llama2_with_chinese_lora_low_mem.py", line 239, in <module>
    tokenizer = LlamaTokenizer.from_pretrained(lora_model_path, legacy=True)
  File "/opt/anaconda3/envs/HackUtil/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "/opt/anaconda3/envs/HackUtil/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/opt/anaconda3/envs/HackUtil/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 156, in __init__
    self.sp_model = self.get_spm_processor()
  File "/opt/anaconda3/envs/HackUtil/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 164, in get_spm_processor
    model_pb2 = import_protobuf()
  File "/opt/anaconda3/envs/HackUtil/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py", line 40, in import_protobuf
    return sentencepiece_model_pb2
UnboundLocalError: local variable 'sentencepiece_model_pb2' referenced before assignment

**Comment by ymcui** [comment]
按要求提供一下依赖情况，另外代码和命令麻烦按提示贴在“代码块”里，方便他人阅读。
