### ISSUE TITLE
报错需要参数output_dir

### ISSUE THREAD

**Issue by Sunnycl** [ymcui/Chinese-LLaMA-Alpaca-2#268]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Linux

### 详细描述问题

昨天微调正常训练，保存参数也正常，今天修改了lora_rank和lora_alpha=128后重新训练，就遇到了这个报错，请问这个错误可能是什么原因？

### 依赖情况（代码类问题务必提供）

```
按代码要求安装的依赖
```

### 运行日志或截图

```
[INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
usage: run_clm_sft_with_peft.py [-h] [--model_name_or_path MODEL_NAME_OR_PATH]
                                [--tokenizer_name_or_path TOKENIZER_NAME_OR_PATH]
                                [--config_overrides CONFIG_OVERRIDES]
                                [--config_name CONFIG_NAME]
                                [--tokenizer_name TOKENIZER_NAME]
                                [--cache_dir CACHE_DIR]
                                [--use_fast_tokenizer [USE_FAST_TOKENIZER]]
                                [--no_use_fast_tokenizer]
                                [--model_revision MODEL_REVISION]
                                [--use_auth_token [USE_AUTH_TOKEN]]
                                [--torch_dtype {auto,bfloat16,float16,float32}]
                                [--dataset_dir DATASET_DIR]
                                [--train_file TRAIN_FILE]
                                [--validation_file VALIDATION_FILE]
                                [--overwrite_cache [OVERWRITE_CACHE]]
                                [--validation_split_percentage VALIDATION_SPLIT_PERCENTAGE]
                                [--preprocessing_num_workers PREPROCESSING_NUM_WORKERS]
                                [--keep_linebreaks [KEEP_LINEBREAKS]]
                                [--no_keep_linebreaks]
                                [--data_cache_dir DATA_CACHE_DIR]
                                [--max_seq_length MAX_SEQ_LENGTH] --output_dir
                                OUTPUT_DIR
                                [--overwrite_output_dir [OVERWRITE_OUTPUT_DIR]]
                                [--do_train [DO_TRAIN]] [--do_eval [DO_EVAL]]
                                [--do_predict [DO_PREDICT]]
                                [--evaluation_strategy {no,steps,epoch}]
                                [--prediction_loss_only [PREDICTION_LOSS_ONLY]]
                                [--per_device_train_batch_size PER_DEVICE_TRAIN_BATCH_SIZE]
                                [--per_device_eval_batch_size PER_DEVICE_EVAL_BATCH_SIZE]
                                [--per_gpu_train_batch_size PER_GPU_TRAIN_BATCH_SIZE]
                                [--per_gpu_eval_batch_size PER_GPU_EVAL_BATCH_SIZE]
                                [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS]
                                [--eval_accumulation_steps EVAL_ACCUMULATION_STEPS]
                                [--eval_delay EVAL_DELAY]
                                [--learning_rate LEARNING_RATE]
                                [--weight_decay WEIGHT_DECAY]
                                [--adam_beta1 ADAM_BETA1]
                                [--adam_beta2 ADAM_BETA2]
                                [--adam_epsilon ADAM_EPSILON]
                                [--max_grad_norm MAX_GRAD_NORM]
                                [--num_train_epochs NUM_TRAIN_EPOCHS]
                                [--max_steps MAX_STEPS]
                                [--lr_scheduler_type {linear,cosine,cosine_with_restarts,polynomial,constant,constant_with_warmup,inverse_sqrt,reduce_lr_on_plateau}]
                                [--warmup_ratio WARMUP_RATIO]
                                [--warmup_steps WARMUP_STEPS]
                                [--log_level {debug,info,warning,error,critical,passive}]
                                [--log_level_replica {debug,info,warning,error,critical,passive}]
                                [--log_on_each_node [LOG_ON_EACH_NODE]]
                                [--no_log_on_each_node]
                                [--logging_dir LOGGING_DIR]
                                [--logging_strategy {no,steps,epoch}]
                                [--logging_first_step [LOGGING_FIRST_STEP]]
                                [--logging_steps LOGGING_STEPS]
                                [--logging_nan_inf_filter [LOGGING_NAN_INF_FILTER]]
                                [--no_logging_nan_inf_filter]
                                [--save_strategy {no,steps,epoch}]
                                [--save_steps SAVE_STEPS]
                                [--save_total_limit SAVE_TOTAL_LIMIT]
                                [--save_safetensors [SAVE_SAFETENSORS]]
                                [--save_on_each_node [SAVE_ON_EACH_NODE]]
                                [--no_cuda [NO_CUDA]]
                                [--use_mps_device [USE_MPS_DEVICE]] [--seed SEED]
                                [--data_seed DATA_SEED]
                                [--jit_mode_eval [JIT_MODE_EVAL]]
                                [--use_ipex [USE_IPEX]] [--bf16 [BF16]]
                                [--fp16 [FP16]] [--fp16_opt_level FP16_OPT_LEVEL]
                                [--half_precision_backend {auto,cuda_amp,apex,cpu_amp}]
                                [--bf16_full_eval [BF16_FULL_EVAL]]
                                [--fp16_full_eval [FP16_FULL_EVAL]] [--tf32 TF32]
                                [--local_rank LOCAL_RANK]
                                [--ddp_backend {nccl,gloo,mpi,ccl}]
                                [--tpu_num_cores TPU_NUM_CORES]
                                [--tpu_metrics_debug [TPU_METRICS_DEBUG]]
                                [--debug DEBUG [DEBUG ...]]
                                [--dataloader_drop_last [DATALOADER_DROP_LAST]]
                                [--eval_steps EVAL_STEPS]
                                [--dataloader_num_workers DATALOADER_NUM_WORKERS]
                                [--past_index PAST_INDEX] [--run_name RUN_NAME]
                                [--disable_tqdm DISABLE_TQDM]
                                [--remove_unused_columns [REMOVE_UNUSED_COLUMNS]]
                                [--no_remove_unused_columns]
                                [--label_names LABEL_NAMES [LABEL_NAMES ...]]
                                [--load_best_model_at_end [LOAD_BEST_MODEL_AT_END]]
                                [--metric_for_best_model METRIC_FOR_BEST_MODEL]
                                [--greater_is_better GREATER_IS_BETTER]
                                [--ignore_data_skip [IGNORE_DATA_SKIP]]
                                [--sharded_ddp SHARDED_DDP] [--fsdp FSDP]
                                [--fsdp_min_num_params FSDP_MIN_NUM_PARAMS]
                                [--fsdp_config FSDP_CONFIG]
                                [--fsdp_transformer_layer_cls_to_wrap FSDP_TRANSFORMER_LAYER_CLS_TO_WRAP]
                                [--deepspeed DEEPSPEED]
                                [--label_smoothing_factor LABEL_SMOOTHING_FACTOR]
                                [--optim {adamw_hf,adamw_torch,adamw_torch_fused,adamw_torch_xla,adamw_apex_fused,adafactor,adamw_anyprecision,sgd,adagrad,adamw_bnb_8bit,adamw_8bit,lion_8bit,lion_32bit,paged_adamw_32bit,paged_adamw_8bit,paged_lion_32bit,paged_lion_8bit}]
                                [--optim_args OPTIM_ARGS]
                                [--adafactor [ADAFACTOR]]
                                [--group_by_length [GROUP_BY_LENGTH]]
                                [--length_column_name LENGTH_COLUMN_NAME]
                                [--report_to REPORT_TO [REPORT_TO ...]]
                                [--ddp_find_unused_parameters DDP_FIND_UNUSED_PARAMETERS]
                                [--ddp_bucket_cap_mb DDP_BUCKET_CAP_MB]
                                [--ddp_broadcast_buffers DDP_BROADCAST_BUFFERS]
                                [--dataloader_pin_memory [DATALOADER_PIN_MEMORY]]
                                [--no_dataloader_pin_memory]
                                [--skip_memory_metrics [SKIP_MEMORY_METRICS]]
                                [--no_skip_memory_metrics]
                                [--use_legacy_prediction_loop [USE_LEGACY_PREDICTION_LOOP]]
                                [--push_to_hub [PUSH_TO_HUB]]
                                [--resume_from_checkpoint RESUME_FROM_CHECKPOINT]
                                [--hub_model_id HUB_MODEL_ID]
                                [--hub_strategy {end,every_save,checkpoint,all_checkpoints}]
                                [--hub_token HUB_TOKEN]
                                [--hub_private_repo [HUB_PRIVATE_REPO]]
                                [--gradient_checkpointing [GRADIENT_CHECKPOINTING]]
                                [--include_inputs_for_metrics [INCLUDE_INPUTS_FOR_METRICS]]
                                [--fp16_backend {auto,cuda_amp,apex,cpu_amp}]
                                [--push_to_hub_model_id PUSH_TO_HUB_MODEL_ID]
                                [--push_to_hub_organization PUSH_TO_HUB_ORGANIZATION]
                                [--push_to_hub_token PUSH_TO_HUB_TOKEN]
                                [--mp_parameters MP_PARAMETERS]
                                [--auto_find_batch_size [AUTO_FIND_BATCH_SIZE]]
                                [--full_determinism [FULL_DETERMINISM]]
                                [--torchdynamo TORCHDYNAMO]
                                [--ray_scope RAY_SCOPE]
                                [--ddp_timeout DDP_TIMEOUT]
                                [--torch_compile [TORCH_COMPILE]]
                                [--torch_compile_backend TORCH_COMPILE_BACKEND]
                                [--torch_compile_mode TORCH_COMPILE_MODE]
                                [--xpu_backend {mpi,ccl,gloo}]
                                [--trainable TRAINABLE] [--lora_rank LORA_RANK]
                                [--lora_dropout LORA_DROPOUT]
                                [--lora_alpha LORA_ALPHA]
                                [--modules_to_save MODULES_TO_SAVE]
                                [--peft_path PEFT_PATH]
                                [--flash_attn [FLASH_ATTN]]
                                [--double_quant [DOUBLE_QUANT]]
                                [--no_double_quant] [--quant_type QUANT_TYPE]
                                [--load_in_kbits LOAD_IN_KBITS]
run_clm_sft_with_peft.py: error: the following arguments are required: --output_dir
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 1381442) of binary: /home/zhangmy/miniconda3/envs/llama2_ch/bin/python
Traceback (most recent call last):
  File "/home/zhangmy/miniconda3/envs/llama2_ch/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.0+cu118', 'console_scripts', 'torchrun')())
  File "/home/zhangmy/miniconda3/envs/llama2_ch/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/zhangmy/miniconda3/envs/llama2_ch/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/zhangmy/miniconda3/envs/llama2_ch/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/zhangmy/miniconda3/envs/llama2_ch/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zhangmy/miniconda3/envs/llama2_ch/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

**Comment by airaria** [comment]
没有提供运行命令没法帮你看啊...不过大概率是命令格式出了问题，如出现多余的空格、或者在行尾漏了`\`等
