### ISSUE TITLE
模型精调训练完成，但是在保存的那一步出现OOM错误

### ISSUE THREAD

**Issue by cheney369** [ymcui/Chinese-LLaMA-Alpaca-2#283]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
单卡T4显存16G，之前按默认参数训练出现OOM错误，把load_in_kbit改成8之后，可以进行训练，但是在保存模型参数的时候出现OOM错误。
尝试将class SavePeftModelCallback(transformers.TrainerCallback) 类中的参数操作修改成下面这样kwargs["model"].to('cpu').save_pretrained(peft_model_path)
kwargs["tokenizer"].save_pretrained(peft_model_path)
可以完成训练那一步，但是在evaluate的时候，会报出数据分布在两个不同设备上的错误。
求助，这种情况下该怎么解决呢？
```

### 依赖情况（代码类问题务必提供）

```
参照requirement.txt版本
```

### 运行日志或截图

```
[INFO|tokenization_utils_base.py:2194] 2023-09-15 14:50:06,318 >> tokenizer config file saved in ../output_dir/sft_lora_model/tokenizer_config.json
[INFO|tokenization_utils_base.py:2201] 2023-09-15 14:50:06,319 >> Special tokens file saved in ../output_dir/sft_lora_model/special_tokens_map.json
Traceback (most recent call last):
  File "run_clm_sft_with_peft.py", line 529, in <module>
    main()
  File "run_clm_sft_with_peft.py", line 502, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2090, in _inner_training_loop
    self.control = self.callback_handler.on_train_end(args, self.state, self.control)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer_callback.py", line 356, in on_train_end
    return self.call_event("on_train_end", args, state, control)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer_callback.py", line 397, in call_event
    result = getattr(callback, event)(
  File "run_clm_sft_with_peft.py", line 79, in on_train_end
    kwargs["model"].to("cuda:0")
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/nn/modules.py", line 294, in to
    return self.cuda(device)
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/nn/modules.py", line 257, in cuda
    B = self.data.contiguous().half().cuda(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 14.76 GiB total capacity; 13.03 GiB already allocated; 43.75 MiB free; 13.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2591) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 11, in <module>
    load_entry_point('torch==2.0.0+cu117', 'console_scripts', 'torchrun')()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm_sft_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-15_14:50:15
  host      : pt_exp
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2591)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

```

**Comment by lichenyigit** [comment]
请教一下，精调用的是run_sft.sh 脚本吗？如果是的话，里边的参数配置可以发一下吗？我精调老是失败·····

**Comment by 459737087** [comment]
你好，你是怎么解决这个问题的 @cheney369

**Comment by lichenyigit** [comment]
更换内存更大的显卡

**Comment by lichenyigit** [comment]
> 你好，你是怎么解决这个问题的 @cheney369

更换内存更大的显卡

**Comment by cheney369** [comment]
我在保存的那一步，把模型移到cpu上，就不会出现这个问题。显卡16G
| |
rcchen30
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | David ***@***.***> |
| 发送日期 | 2023年11月10日 15:04 |
| 收件人 | ymcui/Chinese-LLaMA-Alpaca-2 ***@***.***> |
| 抄送人 | rayChen ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [ymcui/Chinese-LLaMA-Alpaca-2] 模型精调训练完成，但是在保存的那一步出现OOM错误 (Issue #283) |

你好，你是怎么解决这个问题的 @cheney369

**Comment by 459737087** [comment]
你好，关于peft的模型，你用的是什么？ @lichenyigit
