### ISSUE TITLE
模型转换报错

### ISSUE THREAD

**Issue by Ouyang-Wenbin** [ymcui/Chinese-LLaMA-Alpaca-2#287]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型转换和合并

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
模型转换报错
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
ouyang@ouyangwenbindeMacBook-Pro zh-models % cd 7b
ouyang@ouyangwenbindeMacBook-Pro 7b % ll
total 27069416
drwxr-xr-x  13 ouyang  staff          416  9 17 09:07 ./
drwxr-xr-x   6 ouyang  staff          192  9 17 08:45 ../
-rw-r--r--@  1 ouyang  staff         3279  9 17 08:52 README.md
-rw-r--r--@  1 ouyang  staff          720  9 17 08:52 SHA256.md
-rw-r--r--@  1 ouyang  staff          645  9 17 08:52 config.json
-rw-r--r--@  1 ouyang  staff          187  9 17 08:52 generation_config.json
-rw-r--r--@  1 ouyang  staff         1519  9 17 08:52 gitattributes.txt
-rw-r--r--@  1 ouyang  staff  10167475414  9 17 09:07 pytorch_model-00001-of-00002.bin
-rw-r--r--@  1 ouyang  staff   3691156371  9 17 08:56 pytorch_model-00002-of-00002.bin
-rw-r--r--@  1 ouyang  staff        26787  9 17 08:52 pytorch_model.bin.index.json
-rw-r--r--@  1 ouyang  staff          435  9 17 08:52 special_tokens_map.json
-rw-r--r--@  1 ouyang  staff       844403  9 17 08:52 tokenizer.model
-rw-r--r--@  1 ouyang  staff          766  9 17 08:52 tokenizer_config.json


(base) [root@bigdata021200 llama.cpp]# python3 convert.py zh-models/7b/
Loading model file zh-models/7b/pytorch_model-00001-of-00002.bin
Traceback (most recent call last):
  File "/data/llama.cpp/convert.py", line 1208, in <module>
    main()
  File "/data/llama.cpp/convert.py", line 1149, in main
    model_plus = load_some_model(args.model)
  File "/data/llama.cpp/convert.py", line 1069, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "/data/llama.cpp/convert.py", line 758, in lazy_load_file
    return lazy_load_torch_file(fp, path)
  File "/data/llama.cpp/convert.py", line 708, in lazy_load_torch_file
    zf = zipfile.ZipFile(outer_fp)
  File "/root/miniconda3/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/root/miniconda3/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
(base) [root@bigdata021200 llama.cpp]# free -g
              total        used        free      shared  buff/cache   available
Mem:            503         106         108          12         287         382
Swap:             0           0           0
```

**Comment by ymcui** [comment]
1. 拉取最新llama.cpp试试
2. 模型是否完整？可以比对SHA256验证

**Comment by Ouyang-Wenbin** [comment]
🙏谢谢可以了，真的是一个bin的sha256不一样，不知道是不是下载环节出错了😂
