### ISSUE TITLE
在第200step的时候保存模型出现显存溢出，困扰好几天了，求助！

### ISSUE THREAD

**Issue by cheney369** [ymcui/Chinese-LLaMA-Alpaca-2#294]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
设置200step保存一次模型，lora微调。我知道这部分是因为显存不足导致的(但是不知道具体是什么原因)，之前有遇到过类似的，我在保存的时候to("cpu")转移到cpu上，但是你这边的代码不知道要怎么修改才能避免这个问题，求助求帮忙！
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
09/18/2023 14:47:57 - INFO - apscheduler.executors.default - Running job "BaseEmissionsTracker._measure_power (trigger: interval[0:00:15], next run at: 2023-09-18 14:48:12 UTC)" (scheduled at 2023-09-18 14:47:57.547073+00:00)
09/18/2023 14:47:57 - INFO - apscheduler.executors.default - Job "BaseEmissionsTracker._measure_power (trigger: interval[0:00:15], next run at: 2023-09-18 14:48:12 UTC)" executed successfully
{'eval_loss': nan, 'eval_runtime': 218.9083, 'eval_samples_per_second': 2.284, 'eval_steps_per_second': 2.284, 'epoch': 0.08}                                                                           
  8%|████████████▋                                                                                                                                                 | 200/2500 [35:14<5:25:39,  8.50s/it][2023-09-18 14:47:57,729] [INFO] [logging.py:96:log_dist] [Rank 0] [Torch] Checkpoint global_step200 is about to be saved!                                                                              
Traceback (most recent call last):
  File "run_clm_sft_with_peft.py", line 536, in <module>
    main()
  File "run_clm_sft_with_peft.py", line 508, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2020, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2332, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2393, in _save_checkpoint
    self.model_wrapped.save_checkpoint(output_dir)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 3018, in save_checkpoint
    self._save_checkpoint(save_dir,
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 3196, in _save_checkpoint
    module = self.module_state_dict(exclude_frozen_parameters=exclude_frozen_parameters)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 2472, in module_state_dict
    sd = self.module.state_dict(destination, prefix, keep_vars)
  File "run_clm_sft_with_peft.py", line 487, in <lambda>
    lambda self, *_, **__: get_peft_model_state_dict(self, old_state_dict())
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1818, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1818, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1818, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  [Previous line repeated 4 more times]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1815, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/nn/modules.py", line 336, in _save_to_state_dict
    self.weight.data = undo_layout(self.state.CxB, self.state.tile_indices)
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/autograd/_functions.py", line 96, in undo_layout
    outputs = torch.empty_like(tensor)  # note: not using .index_copy because it was slower on cuda
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 14.76 GiB total capacity; 13.28 GiB already allocated; 33.75 MiB free; 13.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  8%|████████████▋                                                                                                                                                 | 200/2500 [35:14<6:45:19, 10.57s/it]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4079) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 11, in <module>
    load_entry_point('torch==2.0.0+cu117', 'console_scripts', 'torchrun')()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm_sft_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-18_14:48:03
  host      : pt_exp
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4079)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

```

**Comment by airaria** [comment]
可能是bitsandbytes的问题，参考这里的讨论：https://github.com/TimDettmers/bitsandbytes/issues/324
