### ISSUE TITLE
使用一些中文文件名和内容的txt文本 PT输出后的模型pt_lora_model，合并推理报错

### ISSUE THREAD

**Issue by ylzong** [ymcui/Chinese-LLaMA-Alpaca-2#306]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

使用一些中文文件名和内容的txt文本 PT输出后的模型pt_lora_model，再进行与原模型chinese-llama-2-7b-hf合并后推理出错了。

pretrained_model=/data/models/chinese-llama-2-7b-hf
chinese_tokenizer_path=/data/models/chinese-llama-2-7b-hf
dataset_dir=/data/txt/xh_txt
data_cache=/data/cache
per_device_train_batch_size=1
gradient_accumulation_steps=8
block_size=512
output_dir=/data/out_llama-2-7b-hf

deepspeed_config_file=ds_zero2_no_offload.json

### 依赖情况（代码类问题务必提供）

bitsandbytes              0.41.0
peft                      0.3.0
sentencepiece             0.1.97
torch                     2.0.1
transformers              4.31.0

### 运行日志或截图

Input length: 37
/opt/app/envs/llama2_evns/lib/python3.10/site-packages/transformers/generation/utils.py:1270: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(
Traceback (most recent call last):
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/routes.py", line 516, in predict
    output = await route_utils.call_process_api(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "/data/agi/Chinese-LLaMA-Alpaca-2/scripts/inference/gradio_demo.py", line 228, in user
    return gr.update(value="", interactive=False), history + \
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
Traceback (most recent call last):
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/utils.py", line 512, in async_iteration
    return await iterator.__anext__()
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/utils.py", line 505, in __anext__
    return await anyio.to_thread.run_sync(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/utils.py", line 488, in run_sync_iterator_async
    return next(iterator)
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/utils.py", line 638, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/data/agi/Chinese-LLaMA-Alpaca-2/scripts/inference/gradio_demo.py", line 362, in predict
    print("len(history):", len(history))
TypeError: object of type 'NoneType' has no len()

**Comment by ymcui** [comment]
那你应该排查一下文件名改成英文能否正常运行？

**Comment by ylzong** [comment]
文件名全改成英文和编号后，进行重新PT生成pt_lora_model后进行推理结果还是报错了。

/opt/app/envs/llama2_evns/lib/python3.10/site-packages/transformers/generation/utils.py:1270: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(
Traceback (most recent call last):
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/routes.py", line 516, in predict
    output = await route_utils.call_process_api(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "/data/agi/Chinese-LLaMA-Alpaca-2/scripts/inference/gradio_demo.py", line 228, in user
    return gr.update(value="", interactive=False), history + \
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
Traceback (most recent call last):
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/utils.py", line 512, in async_iteration
    return await iterator.__anext__()
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/utils.py", line 505, in __anext__
    return await anyio.to_thread.run_sync(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/utils.py", line 488, in run_sync_iterator_async
    return next(iterator)
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/utils.py", line 638, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/opt/app/envs/llama2_evns/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/data/agi/Chinese-LLaMA-Alpaca-2/scripts/inference/gradio_demo.py", line 362, in predict
    print("len(history):", len(history))
TypeError: object of type 'NoneType' has no len()

**Comment by ylzong** [comment]
在对所有文本文件替换掉所有的全角字符后又尝试了一下，再$ python scripts/inference/gradio_demo.py --base_model XXX --lora_model XXX --gpus 0,1,2,3,4,5,6,7后，发现问答有点错乱或回复空。

Running on local URL:  http://0.0.0.0:19324
len(history): 1
history:  [['系统提示语', None]]
Input length: 38
/opt/app/envs/llama2_evns/lib/python3.10/site-packages/transformers/generation/utils.py:1270: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(
len(history): 2
history:  [['系统提示语', '<<SYS>> 是 system prompt, 即系统提示语.'], ['首发企业现场检查规定', None]]
Input length: 68
len(history): 3
history:  [['系统提示语', '<<SYS>> 是 system prompt, 即系统提示语.'], ['首发企业现场检查规定', '<<SYS>> 是 system prompt, 即系统提示语.'], ['你是什么模型？', None]]
Input length: 96
len(history): 1
history:  [['首发企业现场检查规定', None]]
Input length: 40

Could not create share link. Missing file: /opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /opt/app/envs/llama2_evns/lib/python3.10/site-packages/gradio
len(history): 1
history:  [['首发企业现场检查规定', None]]
Input length: 40
len(history): 1
history:  [['你是什么模型？', None]]
Input length: 39
len(history): 1
history:  [['系统提示语', None]]
Input length: 38
len(history): 2
history:  [['系统提示语', '表示该语句是系统提示语而不是用户输入的命令.'], ['你是什么模型？', None]]
Input length: 66
len(history): 1
history:  [['你是什么模型？', None]]
Input length: 39
len(history): 1
history:  [['你是谁？', None]]
Input length: 38

**Comment by iMountTai** [comment]
你保存的`pt_lora_model`, 所以基于chinese-llama-2-7b-hf重新进行了预训练？贴出完整的训练脚本吧，光给几个参数看不懂你的训练配置。
还有就是在你当前的推理脚本中，使用我们发布的模型做一下推理，看看是你脚本推理的bug还是继续训练的模型本身有问题。
另外，中文文件名或者中文字符不影响训练模型的质量，也没有其它影响。
