### ISSUE TITLE
多个.bin怎么合并?或者指定model的名字路径应该是什么?

### ISSUE THREAD

**Issue by fgyang** [ymcui/Chinese-LLaMA-Alpaca-2#325]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Windows

### 详细描述问题

无

### 依赖情况（代码类问题务必提供）

无

### 运行日志或截图

无

**Comment by ymcui** [comment]
说清楚上下文，什么场景下要用到合并后的bin？

**Comment by fgyang** [comment]
大佬,我知道了,我查询了之前的issue,找到方案了,现在是我是用llama.cpp把3各bin,就是hf格式,转换为了ggml的q4_0格式,交互有错误,错误信息如图
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/2727140/2d543cda-4ce4-407e-bef6-dd5d6e683584)
llama_tokenize_with_model: too many tokens这个错误我该如何解决?

**Comment by fgyang** [comment]
Enter a query: 马斯克此次访华可能有什么目的？
llama_tokenize_with_model: too many tokens
Traceback (most recent call last):
  File "F:\privateGPT\privateGPT.py", line 102, in <module>
    main()
  File "F:\privateGPT\privateGPT.py", line 73, in main
    res = qa(query)
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 282, in __call__
    raise e
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 139, in _call
    answer = self.combine_documents_chain.run(
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 480, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 282, in __call__
    raise e
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\combine_documents\base.py", line 105, in _call
    output, extra_return_dict = self.combine_docs(
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\combine_documents\stuff.py", line 171, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\llm.py", line 255, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 282, in __call__
    raise e
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\llm.py", line 91, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\llm.py", line 101, in generate
    return self.llm.generate_prompt(
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\base.py", line 467, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\base.py", line 602, in generate
    output = self._generate_helper(
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\base.py", line 504, in _generate_helper
    raise e
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\base.py", line 491, in _generate_helper
    self._generate(
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\base.py", line 981, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\llamacpp.py", line 254, in _call
    for chunk in self._stream(
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\llamacpp.py", line 304, in _stream
    for part in result:
  File "D:\Program Files\Python310\lib\site-packages\llama_cpp\llama.py", line 901, in _create_completion
    raise ValueError(
ValueError: Requested tokens (1090) exceed context window of 512
Exception ignored in: <function Llama.__del__ at 0x000001A7658064D0>
Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\site-packages\llama_cpp\llama.py", line 1559, in __del__
TypeError: 'NoneType' object is not callable

**Comment by fgyang** [comment]
上面是整个的错误信息

**Comment by ymcui** [comment]
privateGPT？你的`.env`文件如何设置的？`MODEL_N_CTX`设置的值是多少？
这里报错的是`ValueError: Requested tokens (1090) exceed context window of 512`。

**Comment by fgyang** [comment]
MODEL_TYPE=LlamaCpp
PERSIST_DIRECTORY=db
MODEL_PATH=F:/privateGPT/model/chinese-alpaca-2-13b-hf/ggml-model-q8_0.gguf
MODEL_N_CTX=4096
MODEL_N_BATCH=512
EMBEDDINGS_MODEL_NAME=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
TARGET_SOURCE_CHUNKS=4

**Comment by fgyang** [comment]
这里面的512最大可以更改为多少?

**Comment by ymcui** [comment]
清空`db`文件夹，然后尝试降低`MODEL_N_BATCH=8`，重新建索引+测试试一下

**Comment by fgyang** [comment]
更改成2048了,但是错误信息还是一样,如下:
PS F:\privateGPT> python privateGPT.py

Enter a query: hello
llama_tokenize_with_model: too many tokens
Traceback (most recent call last):
  File "F:\privateGPT\privateGPT.py", line 102, in <module>
    main()
  File "F:\privateGPT\privateGPT.py", line 73, in main
    res = qa(query)
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 282, in __call__
    raise e
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 139, in _call
    answer = self.combine_documents_chain.run(
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 480, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 282, in __call__
    raise e
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\combine_documents\base.py", line 105, in _call
    output, extra_return_dict = self.combine_docs(
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\combine_documents\stuff.py", line 171, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\llm.py", line 255, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 282, in __call__
    raise e
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\llm.py", line 91, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "D:\Program Files\Python310\lib\site-packages\langchain\chains\llm.py", line 101, in generate
    return self.llm.generate_prompt(
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\base.py", line 467, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\base.py", line 602, in generate
    output = self._generate_helper(
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\base.py", line 504, in _generate_helper
    raise e
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\base.py", line 491, in _generate_helper
    self._generate(
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\base.py", line 981, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\llamacpp.py", line 254, in _call
    for chunk in self._stream(
  File "D:\Program Files\Python310\lib\site-packages\langchain\llms\llamacpp.py", line 304, in _stream
    for part in result:
  File "D:\Program Files\Python310\lib\site-packages\llama_cpp\llama.py", line 901, in _create_completion
    raise ValueError(
ValueError: Requested tokens (1116) exceed context window of 512
Exception ignored in: <function Llama.__del__ at 0x0000028018CA64D0>
Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\site-packages\llama_cpp\llama.py", line 1559, in __del__
TypeError: 'NoneType' object is not callable
PS F:\privateGPT>

**Comment by ymcui** [comment]
也可以去privateGPT里看看解决方案，有类似的问题：https://github.com/search?q=repo%3Aimartinez%2FprivateGPT+ValueError%3A+Requested+tokens+&type=issues

**Comment by fgyang** [comment]
好的,我更改为8,删除db,重新运行 python ingest.py,然后测试下

**Comment by fgyang** [comment]
删除db,更改为8,重新运行python ingest.py,错误一样,会不会和我的文档特别大有关系,我的word文档86页

**Comment by ymcui** [comment]
1. 你可以用小文档试试
2. 也有人设置`TARGET_SOURCE_CHUNKS = 2`解决了问题

具体还需要自己去试，第三方库的问题我们也没有太多经验。

**Comment by fgyang** [comment]
大佬,我现在ke可以返回但是返回的响应时间及其的慢,有什么办法么？
![Uploading QQ图片20231008204335.png…]()

**Comment by fgyang** [comment]
![QQ图片20231008204335](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/2727140/72960d37-e635-4b7e-ad8c-db773af50727)

**Comment by shirubei** [comment]
今天也碰到这个问题，可以提问者没有给解决方法。试了好几个小时，发现 TARGET_SOURCE_CHUNKS=1 就不会报错了。2都不行。
另外，MODEL_N_BATCH 我也是了一下，拿langchain下的doc.txt(讲李白的那篇文章)测试，感觉 16 还可以，512和4, 2的结果相对于16来说比较差。
为了后来者，留下个痕迹。同时也感谢repo作者的无私分享，Good job !
