### ISSUE TITLE
运行指令精调脚本报错，位置build_dataset.py

### ISSUE THREAD

**Issue by Kong-Chang** [ymcui/Chinese-LLaMA-Alpaca-2#333]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

基于Alpaca-2-7B进行指令精调，运行run_sft.sh时报错；
运行至build_dataset.py的如下代码时：
```
@dataclass
class DataCollatorForSupervisedDataset(object):
    """Collate examples for supervised fine-tuning."""

    tokenizer: transformers.PreTrainedTokenizer

    def __call__(self, instances: Sequence[Dict]) -> Dict[str, torch.Tensor]:
        input_ids, labels = tuple([instance[key] for instance in instances] for key in ("input_ids", "labels"))
        input_ids = torch.nn.utils.rnn.pad_sequence(
            input_ids, batch_first=True, padding_value=self.tokenizer.pad_token_id
        )
        labels = torch.nn.utils.rnn.pad_sequence(labels, batch_first=True, padding_value=-100)
        return dict(
            input_ids=input_ids,
            labels=labels,
            attention_mask=input_ids.ne(self.tokenizer.pad_token_id),
        )
```

self.tokenizer.pad_token_id为None，因此pad_sequence()和ne()都会报错，tokenizer 对象好像没有正确初始化

run_sft.sh如下：
```
lr=1e-4
lora_rank=64
lora_alpha=128
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/gemini/code/llama2/model
chinese_tokenizer_path=/gemini/code/llama2/token
dataset_dir=/gemini/code/llama2/data
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=8
max_seq_length=256
output_dir=/gemini/code/llama2/result
validation_file=/gemini/code/llama2/train/valid.json

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 100 \
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length ${max_seq_length} \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --modules_to_save ${modules_to_save} \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --load_in_kbits 4 \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False
```

### 依赖情况（代码类问题务必提供）

```
transformers  4.31.0
peft  0.3.0.dev0
torch  2.0.1
```

### 运行日志或截图
```
[INFO|trainer.py:1686] 2023-10-11 07:49:09,499 >> ***** Running training *****
[INFO|trainer.py:1687] 2023-10-11 07:49:09,499 >>   Num examples = 2,460
[INFO|trainer.py:1688] 2023-10-11 07:49:09,499 >>   Num Epochs = 1
[INFO|trainer.py:1689] 2023-10-11 07:49:09,499 >>   Instantaneous batch size per device = 1
[INFO|trainer.py:1692] 2023-10-11 07:49:09,499 >>   Total train batch size (w. parallel, distributed & accumulation) = 8
[INFO|trainer.py:1693] 2023-10-11 07:49:09,499 >>   Gradient Accumulation steps = 8
[INFO|trainer.py:1694] 2023-10-11 07:49:09,499 >>   Total optimization steps = 307
[INFO|trainer.py:1695] 2023-10-11 07:49:09,503 >>   Number of trainable parameters = 612,892,672
  0%|                                                                                                                                     | 0/307 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/gemini/code/llama2/train/training/run_clm_sft_with_peft.py", line 529, in <module>
    main()
  File "/gemini/code/llama2/train/training/run_clm_sft_with_peft.py", line 502, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/root/miniconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/root/miniconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1787, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/root/miniconda3/lib/python3.9/site-packages/accelerate/data_loader.py", line 384, in __iter__
    current_batch = next(dataloader_iter)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/gemini/code/llama2/train/training/build_dataset.py", line 96, in __call__
    input_ids = torch.nn.utils.rnn.pad_sequence(
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/utils/rnn.py", line 399, in pad_sequence
    return torch._C._nn.pad_sequence(sequences, batch_first, padding_value)
TypeError: pad_sequence(): argument 'padding_value' (position 3) must be float, not NoneType
  0%|                                                                                                                                     | 0/307 [00:00<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2499) of binary: /root/miniconda3/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm_sft_with_peft.py FAILED
```

**Comment by airaria** [comment]
我们发布的模型文件中的tokenizer是有pad_token的：
```python
tokenizer = LlamaTokenizer.from_pretrained('ziqingyang/chinese-alpaca-2-lora-7b',use_legacy=True)
assert tokenizer.pad_token_id==32000
```
你是否使用加载了正确的tokenizer？

**Comment by Kong-Chang** [comment]
> 我们发布的模型文件中的tokenizer是有pad_token的：
> 
> ```python
> tokenizer = LlamaTokenizer.from_pretrained('ziqingyang/chinese-alpaca-2-lora-7b',use_legacy=True)
> assert tokenizer.pad_token_id==32000
> ```
> 
> 你是否使用加载了正确的tokenizer？

确实是tokenizer路径没放正确，可以跑了，非常感谢！
