### ISSUE TITLE
部署16k完整模型失败 chinese-alpaca-2-13b-16k-hf

### ISSUE THREAD

**Issue by qianxifu** [ymcui/Chinese-LLaMA-Alpaca-2#355]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
部署模型失败，[仿OpenAI API调用](https://platform.openai.com/docs/api-reference)，[text-generation-webui](https://github.com/oobabooga/text-generation-webui)部署都是，提示 please set from_tf=True.
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
bitsandbytes              0.41.0
peft                      0.5.0
sentencepiece             0.1.99
torch                     2.1.0
torch-grammar             0.3.3
transformers              4.35.0.dev0

```

### 运行日志或截图

```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (5.2.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
2023-10-19 12:28:51 WARNING:The --chat flag has been deprecated and will be removed soon. Please remove that flag.
2023-10-19 12:28:51 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
2023-10-19 12:28:55 INFO:Loading chinese-alpaca-2-13b-16k-hf...
Loading checkpoint shards:   0%|                                                                                           | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 485, in load_state_dict
    return torch.load(checkpoint_file, map_location=map_location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 489, in load_state_dict
    if f.read(7) == "version":
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/text-generation-webui/server.py", line 223, in <module>
    shared.model, shared.tokenizer = load_model(model_name)
  File "/root/text-generation-webui/modules/models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "/root/text-generation-webui/modules/models.py", line 219, in huggingface_loader
    model = LoaderClass.from_pretrained(path_to_model, **params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3333, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3709, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 501, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'models/chinese-alpaca-2-13b-16k-hf/pytorch_model-00001-of-00003.bin' at 'models/chinese-alpaca-2-13b-16k-hf/pytorch_model-00001-of-00003.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

**Comment by iMountTai** [comment]
看着像权重不完整，比较一下哈希值？[huggingface哈希值](https://huggingface.co/ziqingyang/chinese-alpaca-2-13b-16k/blob/main/SHA256.md)

**Comment by qianxifu** [comment]
好的，权重是百度网盘上下载的完整模型

**Comment by qianxifu** [comment]
是的，解决了
