### ISSUE TITLE
多机训练会报 CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by 440981** [ymcui/Chinese-LLaMA-Alpaca-2#376]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题
单机跑是没问题的 就是会报显存不足 所以想多机跑 出问题的这台为1050ti 另一台4070ti没问题 两边的cuda版本是一致的
cuda版本
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
```
启动脚本
```
# 运行脚本前请仔细阅读wiki(https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/pt_scripts_zh)
# Read the wiki(https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/pt_scripts_zh) carefully before running the script
lr=2e-4
lora_rank=64
lora_alpha=128
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/mnt/e/LLM/chinese-alpaca-2-13b-hf
chinese_tokenizer_path=/mnt/e/LLM/chinese-alpaca-2-13b-hf
dataset_dir=/mnt/e/LLM/Chinese-LLaMA-Alpaca-2/dataset
data_cache=/mnt/e/LLM/Chinese-LLaMA-Alpaca-2/cache
per_device_train_batch_size=1
gradient_accumulation_steps=8
block_size=8
output_dir=/mnt/d/LLM/Chinese-LLaMA-Alpaca-2/output_dir
CUDA_VISIBLE_DEVICES=1
CUDA_LAUNCH_BLOCKING=1
deepspeed_config_file=ds_zero2_no_offload.json

num_nodes=2
num_gpu_per_node=1
node_rank=0
master_addr=192.168.1.150
master_port=18889

torchrun --nnodes ${num_nodes} \
         --nproc_per_node ${num_gpu_per_node} \
   --node_rank ${node_rank} \
  --master_addr ${master_addr} \
  --master_port ${master_port} \
  run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --do_train \
    --seed $RANDOM \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size ${block_size} \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --modules_to_save ${modules_to_save} \
    --torch_dtype float16 \
    --load_in_kbits 16 \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
[2023-10-31 14:56:56,417] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-31 14:56:59,575] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-10-31 14:56:59,575] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
10/31/2023 14:57:09 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: True
[INFO|configuration_utils.py:710] 2023-10-31 14:57:09,631 >> loading configuration file /mnt/e/LLM/chinese-alpaca-2-13b-hf/config.json
[INFO|configuration_utils.py:768] 2023-10-31 14:57:09,632 >> Model config LlamaConfig {
  "_name_or_path": "/mnt/e/LLM/chinese-alpaca-2-13b-hf",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 13824,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 40,
  "num_hidden_layers": 40,
  "num_key_value_heads": 40,
  "pad_token_id": 0,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.31.0",
  "use_cache": true,
  "vocab_size": 55296
}

[INFO|tokenization_utils_base.py:1837] 2023-10-31 14:57:09,675 >> loading file tokenizer.model
[INFO|tokenization_utils_base.py:1837] 2023-10-31 14:57:09,675 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1837] 2023-10-31 14:57:09,675 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1837] 2023-10-31 14:57:09,675 >> loading file tokenizer_config.json
[WARNING|logging.py:295] 2023-10-31 14:57:09,686 >> You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
10/31/2023 14:57:09 - INFO - __main__ - training datasets-马嘉俊 has been loaded from disk
Caching indices mapping at /mnt/e/LLM/Chinese-LLaMA-Alpaca-2/cache/马嘉俊_8/train/cache-fcf4e2ec95a5f661.arrow
10/31/2023 14:57:09 - INFO - datasets.arrow_dataset - Caching indices mapping at /mnt/e/LLM/Chinese-LLaMA-Alpaca-2/cache/马嘉俊_8/train/cache-fcf4e2ec95a5f661.arrow
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f007bd1d4d7 in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f007bce736b in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f0088a7cfa8 in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x13a0e (0x7f0088a4da0e in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x22d80 (0x7f0088a5cd80 in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x4ccec6 (0x7f007a216ec6 in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3ee77 (0x7f007bd02e77 in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #7: c10::TensorImpl::~TensorImpl() + 0x1be (0x7f007bcfb69e in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #8: c10::TensorImpl::~TensorImpl() + 0x9 (0x7f007bcfb7b9 in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #9: std::vector<at::Tensor, std::allocator<at::Tensor> >::~vector() + 0x8b (0x7f007a21919b in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0xc75a31 (0x7efff9d02a31 in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #11: <unknown function> + 0x538e2d9 (0x7f00244db2d9 in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x539202a (0x7f00244df02a in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x53a0e90 (0x7f00244ede90 in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0xb6bfee (0x7f007a8b5fee in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #15: <unknown function> + 0x3b7285 (0x7f007a101285 in /root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #16: /root/anaconda3/envs/chinese-llama-lora/bin/python() [0x4fc697]
frame #17: _PyObject_MakeTpCall + 0x25b (0x4f614b in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #18: /root/anaconda3/envs/chinese-llama-lora/bin/python() [0x50819f]
frame #19: _PyEval_EvalFrameDefault + 0x13b3 (0x4ee353 in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #20: _PyFunction_Vectorcall + 0x6f (0x4fcadf in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #21: _PyEval_EvalFrameDefault + 0x4b26 (0x4f1ac6 in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #22: /root/anaconda3/envs/chinese-llama-lora/bin/python() [0x56e667]
frame #23: /root/anaconda3/envs/chinese-llama-lora/bin/python() [0x4fccc4]
frame #24: _PyEval_EvalFrameDefault + 0x31f (0x4ed2bf in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #25: /root/anaconda3/envs/chinese-llama-lora/bin/python() [0x507eae]
frame #26: _PyEval_EvalFrameDefault + 0x31f (0x4ed2bf in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #27: _PyFunction_Vectorcall + 0x6f (0x4fcadf in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x31f (0x4ed2bf in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #29: /root/anaconda3/envs/chinese-llama-lora/bin/python() [0x591d92]
frame #30: PyEval_EvalCode + 0x87 (0x591cd7 in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #31: /root/anaconda3/envs/chinese-llama-lora/bin/python() [0x5c2967]
frame #32: /root/anaconda3/envs/chinese-llama-lora/bin/python() [0x5bdad0]
frame #33: /root/anaconda3/envs/chinese-llama-lora/bin/python() [0x45956b]
frame #34: _PyRun_SimpleFileObject + 0x19f (0x5b805f in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #35: _PyRun_AnyFileObject + 0x43 (0x5b7dc3 in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #36: Py_RunMain + 0x38d (0x5b4b7d in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #37: Py_BytesMain + 0x39 (0x584e49 in /root/anaconda3/envs/chinese-llama-lora/bin/python)
frame #38: <unknown function> + 0x29d90 (0x7f00a4224d90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #39: __libc_start_main + 0x80 (0x7f00a4224e40 in /lib/x86_64-linux-gnu/libc.so.6)
frame #40: /root/anaconda3/envs/chinese-llama-lora/bin/python() [0x584cfe]

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 993) of binary: /root/anaconda3/envs/chinese-llama-lora/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/chinese-llama-lora/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/chinese-llama-lora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
====================================================
run_clm_pt_with_peft.py FAILED
----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-31_14:57:12
  host      : majiajun.
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 993)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 993
====================================================
```

**Comment by 440981** [comment]
linux环境为windows的wsl子系统

**Comment by zollty** [comment]
@440981 ，同样的，怎么解决？
```
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch201-cuda-118/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
=====================================================
run_clm_sft_with_peft.py FAILED
-----------------------------------------------------
```

**Comment by 440981** [comment]
> @440981 ，同样的，怎么解决？
> 
> ```
> Traceback (most recent call last):
>   File "/root/anaconda3/envs/pytorch201-cuda-118/bin/torchrun", line 33, in <module>
>     sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
>   File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> =====================================================
> run_clm_sft_with_peft.py FAILED
> -----------------------------------------------------
> ```

没解决呢 有点怀疑是不是两块显卡不一致导致的

**Comment by 440981** [comment]
> > > @440981 ，同样的，怎么解决？
> > > ```
> > > Traceback (most recent call last):
> > >   File "/root/anaconda3/envs/pytorch201-cuda-118/bin/torchrun", line 33, in <module>
> > >     sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
> > >   File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
> > >     return f(*args, **kwargs)
> > >   File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
> > >     run(args)
> > >   File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
> > >     elastic_launch(
> > >   File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
> > >     return launch_agent(self._config, self._entrypoint, list(args))
> > >   File "/root/anaconda3/envs/pytorch201-cuda-118/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
> > >     raise ChildFailedError(
> > > torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> > > =====================================================
> > > run_clm_sft_with_peft.py FAILED
> > > -----------------------------------------------------
> > > ```
> > 
> > 
> > 没解决呢 有点怀疑是不是两块显卡不一致导致的
> 
> 不是显卡问题，我这边单张或多张都是一样的报错。试过去掉 --modules_to_save ${modules_to_save} --gradient_checkpointing 问题依旧，等号后面也没有空格，反正就是报错。

我这边单张都是好的 两台机器就会出现这个错误
