### ISSUE TITLE
使用模型进行摘要出现问题

### ISSUE THREAD

**Issue by 1042312930** [ymcui/Chinese-LLaMA-Alpaca-2#379]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

Chinese-LLaMA-2-16K (7B/13B)

### 操作系统

Windows

### 详细描述问题

```
# 使用教程
#https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/langchain_zh 
# 中的摘要出现了问题
python langchain_sum.py --model_path .\chinese-llama-2-7b-16k-hf\ --file_path doc.txt --gpu_id 0
```

### 依赖情况（代码类问题务必提供）

```
transformers            4.35.0.dev0
peft                    0.6.0.dev0
torch                   2.1.0+cu121
torchaudio              2.1.0+cu121
torchvision             0.16.0+cu121
langchain               0.0.146
sentence-transformers   2.2.2
pydantic                1.10.8
faiss-gpu                1.7.1


```

### 运行日志或截图

```
>python langchain_sum.py --model_path .\chinese-llama-2-7b-16k-hf\ --file_path doc.txt --gpu_id 0

loading LLM...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:53<00:00, 26.96s/it]
C:\Users\zx-cent\.conda\envs\pythonaivenv\lib\site-packages\transformers\generation\configuration_utils.py:381: UserWarning: `do_sample` is set to `False`. However, `temper
ature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializi
ng the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
C:\Users\zx-cent\.conda\envs\pythonaivenv\lib\site-packages\transformers\generation\configuration_utils.py:386: UserWarning: `do_sample` is set to `False`. However, `top_p`
 is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the gener
ation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\zx-cent\PycharmProjects\pythonaimodel\langchain_sum.py", line 53, in <module>                                         
    model = HuggingFacePipeline.from_model_id(model_id=model_path,                                                                     
  File "C:\Users\zx-cent\.conda\envs\pythonaivenv\lib\site-packages\langchain\llms\huggingface_pipeline.py", line 130, in from_model_id
    return cls(                                                                                                                        
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__                                                               
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFacePipeline                                                    
pipeline_kwargs                                                                                                                        
  extra fields not permitted (type=value_error.extra)
```

**Comment by 1042312930** [comment]
模型是使用了这个
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/70195780/3923f7b2-0ce6-480e-9702-45a0c30aeb3e)

**Comment by ymcui** [comment]
1. 你的langchain怎么安装的？看上去应该是安装不正确导致的问题，和模型没有关系。transformers版本和我们的requirements.txt里差距比较大，不排除新版本对接口定义做了修改。要么自行修改，要么就按我们建议的版本进行安装。
2. 模型用的也不对，应该用alpaca系列模型。

**Comment by 1042312930** [comment]
> 1. 你的langchain怎么安装的？看上去应该是安装不正确导致的问题，和模型没有关系。transformers版本和我们的requirements.txt里差距比较大，不排除新版本对接口定义做了修改。要么自行修改，要么就按我们建议的版本进行安装。
> 2. 模型用的也不对，应该用alpaca系列模型。

好的,我再试试应该是模型用错了

**Comment by 1042312930** [comment]
> 1. 你的langchain怎么安装的？看上去应该是安装不正确导致的问题，和模型没有关系。transformers版本和我们的requirements.txt里差距比较大，不排除新版本对接口定义做了修改。要么自行修改，要么就按我们建议的版本进行安装。
> 2. 模型用的也不对，应该用alpaca系列模型。
langchain是直接pip install langchain 安装的
我猜测应该是模型用错了导致把

**Comment by 1042312930** [comment]
> 1. 你的langchain怎么安装的？看上去应该是安装不正确导致的问题，和模型没有关系。transformers版本和我们的requirements.txt里差距比较大，不排除新版本对接口定义做了修改。要么自行修改，要么就按我们建议的版本进行安装。
> 2. 模型用的也不对，应该用alpaca系列模型。

langchain是直接pip install langchain 安装的
我猜测应该是模型用错了导致把
