### ISSUE TITLE
推理载入后出现以下错误，输入数个汉字后，出现该问题。

### ISSUE THREAD

**Issue by q5756578** [ymcui/Chinese-LLaMA-Alpaca-2#380]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```

python3  inference_hf.py \
    --base_model ${global_infer} \
    --lora_model ${lora_Model}\
    --tokenizer_path ${tokenizer_path}\
    --with_prompt \
    --gpus ${nums_gpu} \
    --interactive

```

### 依赖情况（代码类问题务必提供）

```Package            Version
------------------ ------------
accelerate         0.24.0
aiohttp            3.8.6
aiosignal          1.3.1
async-timeout      4.0.3
attrs              23.1.0
bitsandbytes       0.41.0
certifi            2022.12.7
charset-normalizer 2.1.1
cmake              3.25.0
datasets           2.14.6
debugpy            1.8.0
deepspeed          0.11.1
dill               0.3.7
filelock           3.9.0
frozenlist         1.4.0
fsspec             2023.10.0
hjson              3.1.0
huggingface-hub    0.17.3
idna               3.4
Jinja2             3.1.2
joblib             1.3.2
lit                15.0.7
MarkupSafe         2.1.2
mpmath             1.3.0
multidict          6.0.4
multiprocess       0.70.15
networkx           3.0
ninja              1.11.1.1
numpy              1.24.1
packaging          23.2
pandas             2.1.1
peft               0.5.0
Pillow             9.3.0
pip                22.0.2
psutil             5.9.6
py-cpuinfo         9.0.0
pyarrow            13.0.0
pydantic           1.10.13
python-dateutil    2.8.2
pytz               2023.3.post1
PyYAML             6.0.1
regex              2023.10.3
requests           2.28.1
safetensors        0.4.0
scikit-learn       1.3.2
scipy              1.11.3
sentencepiece      0.1.97
setuptools         59.6.0
six                1.16.0
sympy              1.12
threadpoolctl      3.2.0
tokenizers         0.14.1
torch              2.0.1+cu117
torchaudio         2.0.2+cu117
torchvision        0.15.2+cu117
tqdm               4.66.1
transformers       4.34.0
triton             2.0.0
typing_extensions  4.4.0
tzdata             2023.3
urllib3            1.26.13
wheel              0.37.1
xxhash             3.4.1
yarl               1.9.2

```

### 运行日志或截图

```
Xformers is not installed correctly. If you want to use memory_efficient_attention use the following command to install Xformers
pip install xformers.
USE_MEM_EFF_ATTENTION:  False
STORE_KV_BEFORE_ROPE: False
Apply NTK scaling with ALPHA=1.0
The value of scaling factor will be read from model config file, or set to 1.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:27<00:00, 13.88s/it]
Vocab of the base model: 32000
Vocab of the tokenizer: 55296
Resize model embeddings to fit tokenizer
loading peft model
Start inference with instruction mode.
=====================================================================================
+ 该模式下仅支持单轮问答，无多轮对话能力。
+ 如要进行多轮对话，请使用llama.cpp或本项目中的gradio_demo.py。
-------------------------------------------------------------------------------------
+ This mode only supports single-turn QA.
+ If you want to experience multi-turn dialogue, please use llama.cpp or gradio_demo.py.
=====================================================================================
Input:阿斯顿
Traceback (most recent call last):
  File "/root/Chinese-LLaMA-Alpaca-2/scripts/inference/inference_hf.py", line 236, in <module>
    generation_output = model.generate(
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 975, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 1038, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 925, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 635, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
TypeError: xformers_forward() got an unexpected keyword argument 'padding_mask'
```

**Comment by ymcui** [comment]
自己搜一下吧：https://github.com/huggingface/transformers/issues/26755

**Comment by q5756578** [comment]
感谢回复
