### ISSUE TITLE
开启 gradient checkpointing 和 flash-attn2 时 lora sft 在 eval 时报错："use_cache is not supported"

### ISSUE THREAD

**Issue by Huffman-cotdom** [ymcui/Chinese-LLaMA-Alpaca-2#76]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 依赖情况（代码类问题务必提供）

```
peft                     0.4.0
torch                    2.0.1
transformers             4.31.0
```

### 运行日志或截图

开启了 gradient checkpointing，Transformers 会默认将 use_cache=False。
```
[WARNING|logging.py:295] 2023-08-04 11:20:55,373 >> `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
```

但是开启 flash-attn2 时 lora sft 在 eval 时报错："use_cache is not supported"
```
[INFO|trainer.py:3081] 2023-08-04 11:44:30,657 >> ***** Running Evaluation *****
[INFO|trainer.py:3083] 2023-08-04 11:44:30,657 >>   Num examples = 299
[INFO|trainer.py:3086] 2023-08-04 11:44:30,658 >>   Batch size = 16
Traceback (most recent call last):
  File "/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/llm/llm_train/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_sft_with_peft.py", line 507, in <module>
    main()
  File "/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/llm/llm_train/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_sft_with_peft.py", line 480, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/transformers/trainer.py", line 1901, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/transformers/trainer.py", line 2226, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/transformers/trainer.py", line 2934, in evaluate
    output = eval_loop(
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/transformers/trainer.py", line 3123, in evaluation_loop
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/transformers/trainer.py", line 3337, in prediction_step
    loss, outputs = self.compute_loss(model, inputs, return_outputs=True)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in compute_loss
    outputs = model(**inputs)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/peft/peft_model.py", line 922, in forward
    return self.base_model(
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/llm/llm_train/Chinese-LLaMA-Alpaca-2/scripts/training/flash_attn_patch.py", line 59, in forward
    assert not use_cache, "use_cache is not supported"
AssertionError: use_cache is not supported
```

**Comment by iMountTai** [comment]
加载基底模型后设置`model.config.use_cache = False`试试

**Comment by Huffman-cotdom** [comment]
> 加载基底模型后设置`model.config.use_cache = False`试试

我使用以下方式设置 use_cache = False，eval 时没有报错，但是在保存模型之后，模型还是报错
<img width="658" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/63766688/5079cebc-d460-4962-8be5-7664a8dbcb3c">
```
[2023-08-04 14:49:11,493] [INFO] [logging.py:96:log_dist] [Rank 0] [Torch] Checkpoint global_step5 is about to be saved!
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 95822) of binary: /root/miniforge3/envs/flash-atten2/bin/python3.10
Traceback (most recent call last):
  File "/root/miniforge3/envs/flash-atten2/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm_sft_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-04_14:50:05
  host      : mlxlabhzxumawv642e7169-20230406071450-0ptold-88op4n-worker
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 95822)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 95822
============================================================
Exception in thread MsgRouterThr:
Traceback (most recent call last):
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
wandb: ERROR Failed to sample metric: process no longer exists (pid=95822)
    self.run()
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/wandb/sdk/interface/router_queue.py", line 36, in _read_message
    msg = self._response_queue.get(timeout=1)
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/multiprocessing/queues.py", line 117, in get
    res = self._recv_bytes()
  File "/root/miniforge3/envs/flash-atten2/lib/python3.10/multiprocessing/connection.py", line 212, in recv_bytes
  ```

**Comment by Huffman-cotdom** [comment]
> > 加载基底模型后设置`model.config.use_cache = False`试试
> 
> 我使用以下方式设置 use_cache = False，eval 时没有报错，但是在保存模型之后还是报错 <img alt="image" width="658" src="https://user-images.githubusercontent.com/63766688/258327097-5079cebc-d460-4962-8be5-7664a8dbcb3c.png">
> 
> ```
> [2023-08-04 14:49:11,493] [INFO] [logging.py:96:log_dist] [Rank 0] [Torch] Checkpoint global_step5 is about to be saved!
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 95822) of binary: /root/miniforge3/envs/flash-atten2/bin/python3.10
> Traceback (most recent call last):
>   File "/root/miniforge3/envs/flash-atten2/bin/torchrun", line 8, in <module>
>     sys.exit(main())
>   File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> run_clm_sft_with_peft.py FAILED
> ------------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-08-04_14:50:05
>   host      : mlxlabhzxumawv642e7169-20230406071450-0ptold-88op4n-worker
>   rank      : 0 (local_rank: 0)
>   exitcode  : -9 (pid: 95822)
>   error_file: <N/A>
>   traceback : Signal 9 (SIGKILL) received by PID 95822
> ============================================================
> Exception in thread MsgRouterThr:
> Traceback (most recent call last):
>   File "/root/miniforge3/envs/flash-atten2/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
> wandb: ERROR Failed to sample metric: process no longer exists (pid=95822)
>     self.run()
>   File "/root/miniforge3/envs/flash-atten2/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
>     msg = self._read_message()
>   File "/root/miniforge3/envs/flash-atten2/lib/python3.10/site-packages/wandb/sdk/interface/router_queue.py", line 36, in _read_message
>     msg = self._response_queue.get(timeout=1)
>   File "/root/miniforge3/envs/flash-atten2/lib/python3.10/multiprocessing/queues.py", line 117, in get
>     res = self._recv_bytes()
>   File "/root/miniforge3/envs/flash-atten2/lib/python3.10/multiprocessing/connection.py", line 212, in recv_bytes
> ```

https://github.com/tloen/alpaca-lora/issues/338
或许是系统内存不够

**Comment by Huffman-cotdom** [comment]
> > model.config.use_cache = False
> 
> 你好，请问一下，你这个问题解决了吗，我也遇到了你现在这个问题

初始化模型之后使用 model.config.use_cache = False 就可以正常训练了，推理的时候初始化模型之后记得 model.config.use_cache = True 可以加快推理速度

**Comment by zzx16045223** [comment]
> > > model.config.use_cache = False
> > 
> > 
> > 你好，请问一下，你这个问题解决了吗，我也遇到了你现在这个问题
> 
> 初始化模型之后使用 model.config.use_cache = False 就可以正常训练了，推理的时候初始化模型之后记得 model.config.use_cache = True 可以加快推理速度
不好意思啊，我是小白，请问可以帮我指出加在哪里吗？感谢感谢

**Comment by Hang-shao** [comment]
demo中加入 model.config.use_cache = False  为正解。

def init_model(args):
    global tokenizer, model
    tokenizer = AutoTokenizer.from_pretrained(args.tokenizer_path, truncation_side="left", padding_side="left")
    model = AutoModelForCausalLM.from_pretrained(args.model_path, trust_remote_code=True, torch_dtype=torch.bfloat16,
                                                 low_cpu_mem_usage=True, device_map='auto')
    model.generation_config = GenerationConfig.from_pretrained(args.model_path)
    model.generation_config.use_cache = False
    model = model.eval()
