### ISSUE TITLE
使用langchain加载模型失败

### ISSUE THREAD

**Issue by zicheqingluo** [ymcui/Chinese-LLaMA-Alpaca-2#89]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型推理

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
启动项目报错：python langchain_qa.py --embedding_path /data/rd/llm/huggingface.co/text2vec-large-chinese --model_path /data/rd/llm/huggingface.co/chinese-alpaca-2-7b --file_path ./doc.txt  --chain_type refine

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```
sentence-transformers    2.2.2
torch                    2.0.1
torchvision              0.15.2
transformers             4.31.0

### 运行日志或截图

```
# 请在此处粘贴运行日志
```Loading the embedding model...
No sentence-transformers model found with name /data/rd/llm/huggingface.co/text2vec-large-chinese. Creating a new one with MEAN pooling.
loading LLM...
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "/data/rd/llm/Chinese-LLaMA-Alpaca-2/scripts/langchain/langchain_qa.py", line 74, in <module>
    model = HuggingFacePipeline.from_model_id(model_id=model_path,
  File "/data/rd/.pyenv/versions/ch-llama-alpaca2/lib/python3.10/site-packages/langchain/llms/huggingface_pipeline.py", line 88, in from_model_id
    tokenizer = AutoTokenizer.from_pretrained(model_id, **_model_kwargs)
  File "/data/rd/.pyenv/versions/ch-llama-alpaca2/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 702, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/data/rd/.pyenv/versions/ch-llama-alpaca2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1841, in from_pretrained
    return cls._from_pretrained(
  File "/data/rd/.pyenv/versions/ch-llama-alpaca2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1873, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
  File "/data/rd/.pyenv/versions/ch-llama-alpaca2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2004, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/data/rd/.pyenv/versions/ch-llama-alpaca2/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 144, in __init__
    self.sp_model.Load(vocab_file)
  File "/data/rd/.pyenv/versions/ch-llama-alpaca2/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/data/rd/.pyenv/versions/ch-llama-alpaca2/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

**Comment by iMountTai** [comment]
`/data/rd/llm/huggingface.co/chinese-alpaca-2-7b `这个路径下的文件用`ll`列一下

**Comment by zicheqingluo** [comment]
> 

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/50324733/2ecd7c67-36e4-481e-aa40-7b351fc26795)

**Comment by altria-zewei-wang** [comment]
你好 请问您解决这个问题了吗
