### ISSUE TITLE
指令精调训练报错

### ISSUE THREAD

**Issue by ai499** [ymcui/Chinese-LLaMA-Alpaca-2#96]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

```
lr=1e-4
lora_rank=64
lora_alpha=128
lora_trainable="q_proj,v_proj,k_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/root/llama2
chinese_tokenizer_path=/root/llama2
dataset_dir=/root/train_back
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=1
training_steps=300000
output_dir=/root/alpaca_output_2
validation_file=/root/train_laws/laws.json

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 100000 \
    --save_steps 100000 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 1024 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --ddp_find_unused_parameters False

```

### 依赖情况（代码类问题务必提供）

```
Package                  Version
------------------------ -------------
accelerate               0.21.0
aiohttp                  3.8.5
aiosignal                1.3.1
anyio                    3.7.1
async-timeout            4.0.2
attrs                    21.2.0
Automat                  20.2.0
bcrypt                   3.2.0
bitsandbytes             0.39.1
blinker                  1.4
certifi                  2023.5.7
chardet                  4.0.0
charset-normalizer       3.1.0
click                    8.0.3
cloud-init               19.1.21
cmake                    3.27.0
colorama                 0.4.4
coloredlogs              15.0.1
command-not-found        0.3
configobj                5.0.8
constantly               15.1.0
cryptography             3.4.8
cssselect                1.2.0
dataclasses-json         0.5.14
datasets                 2.12.0
dbus-python              1.2.18
ddddocr                  1.4.7
decorator                4.4.2
deepspeed                0.9.3
dill                     0.3.6
distro                   1.7.0
distro-info              1.1build1
exceptiongroup           1.1.2
fastapi                  0.100.1
filelock                 3.12.2
flatbuffers              23.5.26
frozenlist               1.4.0
fsspec                   2023.6.0
greenlet                 2.0.2
h11                      0.14.0
hjson                    3.1.0
httplib2                 0.20.2
huggingface-hub          0.16.4
humanfriendly            10.0
hyperlink                21.0.0
idna                     3.3
importlib-metadata       4.6.4
incremental              21.3.0
iniconfig                2.0.0
jeepney                  0.7.1
Jinja2                   3.1.2
jmespath                 1.0.1
joblib                   1.3.1
jsonpatch                1.32
jsonpointer              2.3
jsonschema               4.17.3
keyring                  23.5.0
langchain                0.0.254
langsmith                0.0.19
launchpadlib             1.10.16
lazr.restfulclient       0.14.4
lazr.uri                 1.0.6
lit                      16.0.6
lxml                     4.9.3
MarkupSafe               2.1.3
marshmallow              3.20.1
more-itertools           8.10.0
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.14
mypy-extensions          1.0.0
netifaces                0.11.0
networkx                 3.1
ninja                    1.11.1
numexpr                  2.8.5
numpy                    1.24.3
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oauthlib                 3.2.2
onnxruntime              1.15.1
openapi-schema-pydantic  1.2.4
opencv-python-headless   4.8.0.74
packaging                23.1
pandas                   2.0.3
parsel                   1.8.1
peft                     0.3.0.dev0
pexpect                  4.8.0
Pillow                   9.4.0
pip                      22.0.2
pluggy                   1.2.0
protobuf                 4.23.4
psutil                   5.9.5
ptyprocess               0.7.0
py-cpuinfo               9.0.0
pyarrow                  12.0.1
pyasn1                   0.4.8
pyasn1-modules           0.2.1
pydantic                 1.10.11
PyGObject                3.42.1
PyHamcrest               2.0.2
PyJWT                    2.3.0
pyOpenSSL                21.0.0
pyparsing                2.4.7
pyrsistent               0.19.3
pyserial                 3.5
pytest                   7.4.0
python-apt               2.4.0+ubuntu1
python-dateutil          2.8.2
python-debian            0.1.43ubuntu1
python-linux-procfs      0.6.3
python-magic             0.4.24
pytz                     2023.3
pyudev                   0.22.0
PyYAML                   6.0
regex                    2023.6.3
requests                 2.31.0
responses                0.18.0
ruff                     0.0.270
safetensors              0.3.1
scikit-learn             1.3.0
scipy                    1.11.1
screen-resolution-extra  0.0.0
SecretStorage            3.3.1
sentencepiece            0.1.97
service-identity         18.1.0
setuptools               59.6.0
shortuuid                1.0.11
six                      1.16.0
sniffio                  1.3.0
sos                      4.4
SQLAlchemy               2.0.19
ssh-import-id            5.11
starlette                0.27.0
sympy                    1.12
systemd-python           234
tenacity                 8.2.2
threadpoolctl            3.2.0
tokenizers               0.13.3
tomli                    2.0.1
torch                    2.0.1
tqdm                     4.65.0
transformers             4.31.0
triton                   2.0.0
Twisted                  22.1.0
typing_extensions        4.7.1
typing-inspect           0.9.0
tzdata                   2023.3
ubuntu-advantage-tools   8001
ubuntu-drivers-common    0.0.0
ufw                      0.36.1
unattended-upgrades      0.1
urllib3                  2.0.3
uvicorn                  0.23.1
w3lib                    2.1.1
wadllib                  1.3.6
wheel                    0.37.1
xkit                     0.0.0
xxhash                   3.2.0
yarl                     1.9.2
zipp                     1.0.0
zope.interface           5.4.0
```

### 运行日志或截图

```
[INFO|trainer.py:1686] 2023-08-08 08:32:30,650 >> ***** Running training *****
[INFO|trainer.py:1687] 2023-08-08 08:32:30,650 >>   Num examples = 4,133,914
[INFO|trainer.py:1688] 2023-08-08 08:32:30,650 >>   Num Epochs = 1
[INFO|trainer.py:1689] 2023-08-08 08:32:30,650 >>   Instantaneous batch size per device = 1
[INFO|trainer.py:1692] 2023-08-08 08:32:30,650 >>   Total train batch size (w. parallel, distributed & accumulation) = 1
[INFO|trainer.py:1693] 2023-08-08 08:32:30,650 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:1694] 2023-08-08 08:32:30,650 >>   Total optimization steps = 4,133,914
[INFO|trainer.py:1695] 2023-08-08 08:32:30,652 >>   Number of trainable parameters = 576,061,440
  0%|                                                                                                                                       | 0/4133914 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_sft_with_peft.py", line 435, in <module>
    main()
  File "/root/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_sft_with_peft.py", line 408, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1787, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/usr/local/lib/python3.10/dist-packages/accelerate/data_loader.py", line 384, in __iter__
    current_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/root/Chinese-LLaMA-Alpaca-2/scripts/training/build_dataset.py", line 96, in __call__
    input_ids = torch.nn.utils.rnn.pad_sequence(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/utils/rnn.py", line 399, in pad_sequence
    return torch._C._nn.pad_sequence(sequences, batch_first, padding_value)
TypeError: pad_sequence(): argument 'padding_value' (position 3) must be float, not NoneType
  0%|                                                                                                                                       | 0/4133914 [00:00<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 189482) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm_sft_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-08_08:32:33
  host      : iZwz9fln7i705qdim3nhu5Z
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 189482)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by ai499** [comment]
pretrained_model模型为原版hf 7b模型经过预训练后的结果，在进行指令精调时报错

**Comment by airaria** [comment]
你用的pretrained_model是原版llama2 32000词表的，还是词表扩充后的？

**Comment by ai499** [comment]
扩充后的

**Comment by ai499** [comment]
total 840K
drwxr-xr-x  2 root root 4.0K Jul 31 18:31 .
drwx------ 50 root root 4.0K Aug  8 11:37 ..
-rw-r--r--  1 root root  748 Jul 27 12:41 tokenizer_config.json
-rw-r--r--  1 root root 825K Jul 27 12:41 tokenizer.model

**Comment by airaria** [comment]
从报错信息看tokenizer不太对，你检查一下tokenizer的词表大小
```python
from transformers import LlamaTokenizer
tokenizer = LlamaTokenizer.from_pretrained('path/to/your/tokenizer')
print(len(tokenizer))
print(tokenizer.special_tokens_map)
print(tokenizer.pad_token_id)
```

**Comment by ai499** [comment]
>>> from transformers import LlamaTokenizer
>>> tokenizer = LlamaTokenizer.from_pretrained('/root/hrxllama2')
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
>>> print(len(tokenizer))
55296
>>> print(tokenizer.special_tokens_map)
{'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>'}
>>> print(tokenizer.pad_token_id)
None

**Comment by ai499** [comment]
`{'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>'}`

**Comment by airaria** [comment]
> 我也碰到类似问题，输出是：
> 
> ```
> You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
> >>> print(len(tokenizer))
> 55296
> >>> print(tokenizer.special_tokens_map)
> {'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '<pad>'}
> >>> print(tokenizer.pad_token_id)
> 32000
> ```

这个结果没问题。如果你遇到其他问题，建议开一个新issue提问。

 @ai499 tokenizer里少了pad_token, 参考 @BenRood8165290 的输出，这个是正常的。建议重新下载tokenizer相关文件。

**Comment by ai499** [comment]
@airaria 重下载了一个好了 谢谢大佬

**Comment by BenRood8165290** [comment]
> 这个结果没问题。如果你遇到其他问题，建议开一个新issue提问。
哦，可能我碰到的错误和AutoGPTQ版本有关，我是转换成gptq 4bit 32g然后再通过llm_tuning去快速训练的，最初是batchsize 4模式转换的，碰到了错误（you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565）。后来尝试了batchsize 1转换没碰到这个错误。
再往后又用batchsize 4转换，也正常了。（期间可能更新过AutoGPTQ）

**Comment by enelguo** [comment]
各位大佬，我也遇到了tokenizer词表的问题，无论我去百度，google或者hugginface上面down下来的tokenizer.model都是32000的长度。
代码用的 @airaria 大佬提供的，结果是这样：
------------------------------------
32000
{'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>'}
None
------------------------------------
我看了依赖包，有一些不一样，主要的依赖都和楼主一样的，请大佬帮忙看看，感谢！！

**Comment by conjugalmaritalharmony** [comment]
> `{'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>'}`

TypeError: pad_sequence(): argument 'padding_value' (position 3) must be float, not NoneType
我也遇见了类似问题，想要使用Chinese-Alpaca为base模型，指令精调全新的LoRA。然而，单机多卡时报错。也重新下了tokenizer.model。还是遇见相同报错，问下大佬怎么操作呢

**Comment by airaria** [comment]
> > `{'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>'}`
> 
> TypeError: pad_sequence(): argument 'padding_value' (position 3) must be float, not NoneType 我也遇见了类似问题，想要使用Chinese-Alpaca为base模型，指令精调全新的LoRA。然而，单机多卡时报错。也重新下了tokenizer.model。还是遇见相同报错，问下大佬怎么操作呢

只重下了tokenizer.model吗？相关config有没有更新？

**Comment by conjugalmaritalharmony** [comment]
我重新下了https://huggingface.co/ziqingyang/chinese-llama-2-lora-13b中的相关config，已经可以跑起来了，谢谢大佬。

**Comment by huxiaosheng123** [comment]
可以参考：https://github.com/huxiaosheng123/open-llama2

**Comment by 20191864218** [comment]
> > > `{'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>'}`
> > 
> > 
> > TypeError: pad_sequence(): argument 'padding_value' (position 3) must be float, not NoneType 我也遇见了类似问题，想要使用Chinese-Alpaca为base模型，指令精调全新的LoRA。然而，单机多卡时报错。也重新下了tokenizer.model。还是遇见相同报错，问下大佬怎么操作呢
> 
> 只重下了tokenizer.model吗？相关config有没有更新？

大佬您好，我在替换LLaVA的LLM为Qwen的时候，碰见了同样的错误，tokenizer相关的文件全都重新更新了，还是这个错误，请问大佬有什么解决办法吗
