### ISSUE TITLE
Exception: Current loss scale already at minimum - cannot decrease scale anymore. Exiting run.

### ISSUE THREAD

**Issue by YinSonglin1997** [ymcui/Chinese-LLaMA-Alpaca-2#97]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

None

### 操作系统

Linux

### 详细描述问题

采用您的框架对llama2-7b的基座模型进行二次预训练，训练能够进行，但在进行过程中一直在[deepspeed] OVERFLOW!，直到最终Attempted loss scale: 0 ，最终报标题的错误。请问这种情况如何解决？
```
[2023-08-07 18:35:18,432] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 0, reducing to 0
  0%|                                                        | 94/97976 [1:27:41<1515:27:58, 55.74s/it][2023-08-07 18:38:05,632] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 0, reducing to 0
  0%|                                                        | 95/97976 [1:28:37<1514:49:16, 55.71s/it]Traceback (most recent call last):
  File "/ldata/llms/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_pt_with_peft.py", line 638, in <module>
    main()
  File "/ldata/llms/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_pt_with_peft.py", line 606, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/transformers/trainer.py", line 2665, in training_step
    self.accelerator.backward(loss)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/accelerate/accelerator.py", line 1847, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 176, in backward
    self.engine.step()
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2087, in step
    self._take_model_step(lr_kwargs)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1994, in _take_model_step
    self.optimizer.step()
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1662, in step
    self._update_scale(self.overflow)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1908, in _update_scale
    self.loss_scaler.update_scale(has_overflow)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 175, in update_scale
    raise Exception(
Exception: Current loss scale already at minimum - cannot decrease scale anymore. Exiting run.

```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by iMountTai** [comment]
可以尝试`bf16`训练
